### ISSUE TITLE
broken style

### ISSUE THREAD

**Issue by kapcom01** [g1eny0ung/hugo-theme-dream#10]
I have to refresh many times to get the site to render correctly. Most of the time, the site renders like this:
![default](https://user-images.githubusercontent.com/21684/48657955-6bac5f80-ea42-11e8-8ac6-fdbf5cd00540.png)

I think it has something to do with CDN failing to load.

**Comment by g1eny0ung** [comment]
I test in my laptop and the resource files load normally. Is there any errors in your browser dev tools?

**Comment by kapcom01** [comment]
![image](https://user-images.githubusercontent.com/21684/48967481-c36e3c00-efe9-11e8-8cfc-cdd6454284b6.png)

**Comment by g1eny0ung** [comment]
Sure, it's easy to change cdn links to local static links. I will update soon.

**Comment by g1eny0ung** [comment]
Update in https://github.com/g1eny0ung/hugo-theme-dream/commit/65acf52577cc89f13b7b8e00896b578bfd79c491

**Comment by kapcom01** [comment]
Thank you! You are the best :1st_place_medal:
