### ISSUE TITLE
Home button link to the root "/" dir instead of sub dir

### ISSUE THREAD

**Issue by n13r** [g1eny0ung/hugo-theme-dream#100]
My site is www.mysite.com/demo/ and all the page, css and js are working well with the adding option "CanonifyURLs = true". but the issue is on the home button on the top left corner is link to the root dir instead of my sub dir /demo/ when i check in the index.html or 404.html i find out that it used javascript to link (onclick="window.location.href = '/'), so how to fix it without custom edit line by line and page by page?

**Comment by g1eny0ung** [comment]
I found a solution. What about changing the baseURL with the sub dir in your `config.toml`. Like `baseURL = https://mysite.com/demo`.

And modify `layouts/partials/back.html` with:

```
<i class="large link home icon" title="{{ i18n "home" }}" onclick="window.location.href = {{ .Site.BaseURL }}"></i>
```

But what I'm not sure is the `baseURL` with sub dir maybe cause some unexpected problems. If everything is fine on your website, I will change the `/` to `.Site.BaseURL`.

**Comment by n13r** [comment]
Okay thank you for your response, and let me try the solution you provide above. :)

**Comment by g1eny0ung** [comment]
https://github.com/g1eny0ung/hugo-theme-dream/blob/df1a96e449fe7df124ef8b1788d94e0e578a20fd/layouts/partials/nav.html#L10

Try to replace this line. 😺

**Comment by n13r** [comment]
hahhh so it on nav.html not back.html..... lol and yeah i made it working now... thank you for your good response, have a nice day bro.

**Comment by g1eny0ung** [comment]
@n13r So sorry about it 🤣, I mistakenly wrote `nav` as `back`.

**Comment by n13r** [comment]
Yeah sure...

**Comment by g1eny0ung** [comment]
👌
