### ISSUE TITLE
How to pagination?

### ISSUE THREAD

**Issue by aalfiann** [g1eny0ung/hugo-theme-dream#102]
How to use pagination in this theme?

**Comment by g1eny0ung** [comment]
Currently, there is no pagination because I rewrite the whole theme recently. I will add it soon.

**Comment by aalfiann** [comment]
Thank you.. It sounds great, because if we have more than 50 design project, website will load very slow because too many images loaded in one page. So pagination must be there..

**Comment by icannaci** [comment]
网页为什么显示不了图片？：（

**Comment by g1eny0ung** [comment]
@aalfiann Complete in 9f85d8f7c87809414f5ca22568626875bc3d879a.

**Comment by g1eny0ung** [comment]
Long time no response, temporarily closed.

**Comment by aalfiann** [comment]
Thank you bro.. Sorry, I forgot to reply and close this issue..

**Comment by g1eny0ung** [comment]
Not mid.~
