### ISSUE TITLE
如何显示归档图标

### ISSUE THREAD

**Issue by moyunying** [g1eny0ung/hugo-theme-dream#103]
我按照叫教学文档在content/post下加了一个_index.md文件，但是没有显示归档图标，只有标签和分类。求教，感激不尽！
<img width="451" alt="2020-02-02" src="https://user-images.githubusercontent.com/60456704/73602683-16129300-45b3-11ea-8b4c-21adef44ea2d.png">

**Comment by g1eny0ung** [comment]
content/**post** 变成 content/**posts** 应该就可以了。

**Comment by moyunying** [comment]
解决了，谢谢！
很喜欢你的主题！
