### ISSUE TITLE
阅读时间

### ISSUE THREAD

**Issue by moyunying** [g1eny0ung/hugo-theme-dream#106]
请问博文的阅读时间可以改吗，我的博文的阅读时间都是一分钟。

**Comment by g1eny0ung** [comment]
你的博客内容是中文吗，如果是的话需要在 `config.toml` 加上 `hasCJKLanguage = true`。

参考：https://g1eny0ung.site/hugo-theme-dream/#/base-configurations

**Comment by moyunying** [comment]
谢谢你！
