### ISSUE TITLE
Vertical scroll is hidden

### ISSUE THREAD

**Issue by mrbinr** [g1eny0ung/hugo-theme-dream#107]
Hi,
How to have vertical scroll ?
On small computer screen size i need to have vertical scroll to allow users to have whole content.

Thanks,
Best regards
Pascall

**Comment by g1eny0ung** [comment]
Is there has anything screen adaptation issues?

Maybe providing a screenshot can make me understand a little bit more.

**Comment by mrbinr** [comment]
Hi
here is a [screenshot](http://cdn.etunepinceede.fr/eupd.png)
as you can see there is no scrollbar on the right ...
the only way to scroll is to use mousewheel

**Comment by g1eny0ung** [comment]
I know what you mean. 👍 I already fix it in b7b832b155192a1c12816d683f4137ea4608d70b.

**Comment by mrbinr** [comment]
great job !
thanks a lot.
