### ISSUE TITLE
How to change font-size?

### ISSUE THREAD

**Issue by susiShushi** [g1eny0ung/hugo-theme-dream#108]
Thank you for a great theme. I have one question: how to change font-size in this theme?

**Comment by g1eny0ung** [comment]
You can customize by yourself. 

Install node.js and run `yarn dev` to watch the `.scss` files' change. The entry file is https://github.com/g1eny0ung/hugo-theme-dream/blob/master/src/sass/site.scss

When you‘re done, run `yarn prod` to compress the styles.

**Comment by susiShushi** [comment]
Aha, thank you so much! I can customize it!

**Comment by g1eny0ung** [comment]
> Aha, thank you so much! I can customize it!

Haha, glad to help you.

**Comment by vutruong99** [comment]
> 
> 
> > Aha, thank you so much! I can customize it!
> 
> Haha, glad to help you.

hey bro. I love your work. I'm having trouble changing the font of the posts too. I'm not sure what I should do after "yarn dev", it just says  Starting 'watch'...
               Starting 'sassWatch'...
               Starting 'jsWatch'...
can you help me a bit?

**Comment by g1eny0ung** [comment]
After running `yarn dev`, modifying the file under `src` will trigger an automatic build (put the modified file under `static`).

BTW: this method has been replaced by two configuration params: `customCSS` and `customJS`. You can refer to https://g1eny0ung.site/hugo-theme-dream/#/params-configurations?id=advanced for its usage.

**Comment by vutruong99** [comment]
> 
> 
> After running `yarn dev`, modifying the file under `src` will trigger an automatic build (put the modified file under `static`).
> 
> BTW: this method has been replaced by two configuration params: `customCSS` and `customJS`. You can refer to https://g1eny0ung.site/hugo-theme-dream/#/params-configurations?id=advanced for its usage.

oh thank you so much, I thought that fonts cant be adjusted through custom CSS. My bad. Thanks again!
