### ISSUE TITLE
图片配置和分类配置

### ISSUE THREAD

**Issue by HaidongSong** [g1eny0ung/hugo-theme-dream#109]
# 感谢大佬的主题，很漂亮，配置的时候遇到点问题，求助
## 2. 分类设置在哪里？设置成你那样
![enter description here](https://gitee.com/margan/pictures/raw/master/小书匠/1584415782951.png)
设置成
![enter description here](https://gitee.com/margan/pictures/raw/master/小书匠/1584415828710.png)
## 3. 文章长度显示怎么设置？（不要让它像这样？）
![enter description here](https://gitee.com/margan/pictures/raw/master/小书匠/1584415699172.png)

## 4. 如果不想显示任何图片，怎么设置？
![enter description here](https://gitee.com/margan/pictures/raw/master/小书匠/1584419409170.png)

**Comment by g1eny0ung** [comment]
1. 图片放在 static 文件夹下面，路径自定义就可以。
2. 分类参考  https://gohugo.io/content-management/front-matter/#example 这里，写在 front matter 里面。
3. https://github.com/g1eny0ung/hugo-theme-dream/blob/master/archetypes/posts.md 参考默认模版，简介写在 `<!--more-->` 上面。
4. 不想显示图片的话，注释掉这里 6-12 行：https://github.com/g1eny0ung/hugo-theme-dream/blob/master/layouts/_default/summary.html#L6

**Comment by HaidongSong** [comment]
@g1eny0ung 非常感谢。还有两个问题。
1. 怎么能让博客支持markdown的甘特图?
2. 怎么控制一页中显示的文章数量?

**Comment by g1eny0ung** [comment]
1. 默认应该是不支持甘特图的，应该需要用 JS 去画。
2. 在 `config.toml` 里面加上 `paginate = number` 即可。

**Comment by HaidongSong** [comment]
@g1eny0ung 非常感谢，问题基本都解决了，还差甘特图的支持，我在慢慢研究下吧。

**Comment by g1eny0ung** [comment]
不客气，用 [Hugo shortcodes](https://gohugo.io/content-management/shortcodes/) 和一个 js 的甘特图的库就可以实现了。

**Comment by HaidongSong** [comment]
@g1eny0ung 再次感谢，怎么支持[doc]啊?
我config.toml添加这样设置的后没有生效。
···
[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2
···

**Comment by g1eny0ung** [comment]
因为我没加 TOC，所以肯定无法生效呀 🤣。

可以自己加一下，参考这个：https://gohugo.io/content-management/toc/

**Comment by HaidongSong** [comment]
### 我按照你发的那个链接做了这样的设置，还是无法生效🤣。(我也添加了)你知道这是为啥吗？
![enter description here](https://gitee.com/margan/pictures/raw/master/小书匠/1584527008657.png)
我用另一种方式添加了toc.html也不行？
![enter description here](https://gitee.com/margan/pictures/raw/master/小书匠/1584527691680.png)

**Comment by g1eny0ung** [comment]
这我就看不出来了，如果你想让配置 `[markup.tableOfContents]` 生效，首先得有 TOC，你这个已经做到这一步了，再看看文档调试一下吧。

**Comment by HaidongSong** [comment]
@g1eny0ung 
![enter description here](https://gitee.com/margan/pictures/raw/master/小书匠/1584531055230.png)
有啊？🤣
