### ISSUE TITLE
新的报警

### ISSUE THREAD

**Issue by user1121114685** [g1eny0ung/hugo-theme-dream#11]
The page build failed for the `master` branch with the following error:

The tag `image` on line 129 in `themes/dream/exampleSite/content/post/migrate-from-jekyll.md` is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.

For information on troubleshooting Jekyll see:

大佬还望修复！！

**Comment by g1eny0ung** [comment]
没怎么明白你的意思呀，我跑了一下，没发现错误

**Comment by user1121114685** [comment]
> 没怎么明白你的意思呀，我跑了一下，没发现错误

我也不知道为什么，我把这文件删了还是报警。。。。可能是我打开方式不对！

**Comment by user1121114685** [comment]
```
git clone https://github.com/g1eny0ung/hugo-theme-dream.git themes/dream
git submodule add https://github.com/g1eny0ung/hugo-theme-dream.git themes/dream
```

> 我懂了大佬，GitHub Pages 默认的是Jekyll 所以他就一直报警。。。
> 大佬我已经直接订阅的你的主题了！不知道有没有影响！

**Comment by g1eny0ung** [comment]
OK，当然木有影响 😃。那么我就关闭 issue 了

**Comment by user1121114685** [comment]
> OK，当然木有影响 😃。那么我就关闭 issue 了

谢谢大佬了，是你的主题让我走上了小白写博客之路！谢谢！
