### ISSUE TITLE
图片配置无效

### ISSUE THREAD

**Issue by cym2050** [g1eny0ung/hugo-theme-dream#110]
**你好，在使用hugo0.69.0版本时添加自定义图片无效，不知是我配置问题还是hugo版本问题**
```
---
title: Ceshi
date: 2020-04-17T17:29:33+08:00
lastmod: 2020-04-17T17:29:33+08:00
author: Author Name
cover: ceshi1/static/white-rose-1713953.jpg
categories: ["category1"]
tags: ["tag1", "tag2"]
# showcase: true
draft: false
---
```
![image](https://user-images.githubusercontent.com/28197412/79558702-28db3500-80d7-11ea-9549-6aed944eb74d.png)

**Comment by g1eny0ung** [comment]
图片是相对于 `static` 目录的，比如你的 `static` 目录下面有一张图片叫 `a,png`，那么你只需要写 `/a.png` 就可以了。

**Comment by cym2050** [comment]
> 图片是相对于 `static` 目录的，比如你的 `static` 目录下面有一张图片叫 `a.png`，那么你只需要写 `/a.png` 就可以了。

谢谢，问题解决。
