### ISSUE TITLE
On dark mode, the flip icon disappear

### ISSUE THREAD

**Issue by Agosh13** [g1eny0ung/hugo-theme-dream#111]
Ciao, thanks for this great work.
With the dark mode feature, I noticed that the flip icon disappear on flipped ui.
I think it's only a

**Comment by g1eny0ung** [comment]
Thx for reminding. Fixed in 72189b95faa10eb479944cb65e29f08c9a17d235.

**Comment by g1eny0ung** [comment]
Long time no response, closed.
