### ISSUE TITLE
New social 

### ISSUE THREAD

**Issue by Agosh13** [g1eny0ung/hugo-theme-dream#112]
Ciao, could you please add these new social?
I've already added them in partials:

         {{ if .Site.Params.twitter }}
            <div class="item">
              <a href="https://www.twitter.com/{{ .Site.Params.twitter }}" target="_blank">
                <i class="large twitter icon" title="twitter"></i>
              </a>
            </div>
          {{ end }}

          {{ if .Site.Params.facebook }}
            <div class="item">
              <a href="https://www.facebook.com/{{ .Site.Params.twitter }}" target="_blank">
                <i class="large facebook icon" title="facebook"></i>
              </a>
            </div>
          {{ end }}

          {{ if .Site.Params.facebook }}
            <div class="item">
              <a href="https://www.instagram.com/{{ .Site.Params.twitter }}" target="_blank">
                <i class="large instagram icon" title="instagram"></i>
              </a>
            </div>
          {{ end }}

Also, I've added all social under the categories and tags button, it's looks great, it could be a new features.

**Comment by g1eny0ung** [comment]
> Also, I've added all social under the categories and tags button, it's looks great, it could be a new features.

LGTM. I will add these later.

**Comment by g1eny0ung** [comment]
@Agosh13 Done in 339ac47efb6c7be8ab124e25a2ef70768f6fd300.

**Comment by g1eny0ung** [comment]
Long time no response, closed.
