### ISSUE TITLE
Can you add a search bar (Not an issue)

### ISSUE THREAD

**Issue by rushic24** [g1eny0ung/hugo-theme-dream#113]

**Comment by g1eny0ung** [comment]
Good idea. I can add it, but I think a search page is more usable than a search bar. If you let me choose, I will choose a separate search page.

**Comment by rushic24** [comment]
Anything  just something to search through posts/ titles.

**Comment by g1eny0ung** [comment]
Ok, I will think about how to achieve this.

**Comment by aalfiann** [comment]
Generate index.json for all title and description posts.. Then you're able to add javascript for the query search function.

**Comment by saucesaft** [comment]
These websites could help:
https://gohugo.io/tools/search/
https://www.npmjs.com/package/hugo-lunr
https://www.npmjs.com/package/hugo-search-index

**Comment by g1eny0ung** [comment]
Hi, guys. I finish the search feature. Sorry for waiting so long, because I was too busy some time ago.

Here is the doc: https://g1eny0ung.site/hugo-theme-dream/#/search.

Hope you can use it happily.~

**Comment by rushic24** [comment]
Thank you so much :-)

**Comment by g1eny0ung** [comment]
I will close this issue for now. If you have any questions about searching,feel free to reopen it.~
