### ISSUE TITLE
Markdown code blocks unreadable in dark mode

### ISSUE THREAD

**Issue by zuoshihua** [g1eny0ung/hugo-theme-dream#114]
When switching to dark mode, text in code blocks are difficult to read.
![image](https://user-images.githubusercontent.com/64007522/79736939-28d47280-832d-11ea-8774-b3ff9b9dfc1b.png)

**Comment by g1eny0ung** [comment]
Try to give a language name after code block, like **```rust**.

**Comment by zuoshihua** [comment]
Thanks for the tip! However I think it would be great if the code blocks support light and dark mode

**Comment by g1eny0ung** [comment]
> However I think it would be great if the code blocks support light and dark mode

LGTM. I will add it in the future.
