### ISSUE TITLE
Tiled layout for loveit

### ISSUE THREAD

**Issue by chain-ed-reaction** [g1eny0ung/hugo-theme-dream#116]
Hi,
I like the tiled layout for your theme. Could you let me know how one would go about such a layout for the loveit theme. I require it for a collaboration and love everything else about loveit theme. Any advice would be appreciated.
Note: only the arrangement of posts  is what i am asking about. I think it should be pretty simple, but due to my inexperience with web development, Im not able to do it without some help
The related issue in loveit repo
https://github.com/dillonzq/LoveIt/issues/332#issue-613740755

**Comment by g1eny0ung** [comment]
I am not sure if I fully understand what you mean.

 Is the tiled layout you described is the archive page of hugo-theme-dream?

Actual effect: https://g1eny0ung.site/posts/

**Comment by chain-ed-reaction** [comment]
The home page I mean

**Comment by chain-ed-reaction** [comment]
We are considering the dream theme now. Would have been really great if we could have the best of both worlds!

**Comment by g1eny0ung** [comment]
Thx. It's not difficult to implement this. I use https://masonry.desandro.com/ to implement the home page layout.

The source code can be found in https://github.com/g1eny0ung/hugo-theme-dream/blob/master/src/js/main.js#L8

**Comment by chain-ed-reaction** [comment]
Thanks for the reply will try it out!
