### ISSUE TITLE
主题插件问题

### ISSUE THREAD

**Issue by Yafine** [g1eny0ung/hugo-theme-dream#117]
您好，请问一下，这个文章保存为图片是如何实现的呢？

**Comment by g1eny0ung** [comment]
在这里，canvas to img。

https://github.com/g1eny0ung/hugo-theme-dream/blob/a8f9d26f817749112ad3fcb2491a329c0768aa85/src/js/main.js#L18

**Comment by g1eny0ung** [comment]
Long time no response. Temporarily closed.

**Comment by g1eny0ung** [comment]
Long time no response, temporarily closed.
