### ISSUE TITLE
大佬你好再次打扰了，请问可以设置触发图片url替换吗？

### ISSUE THREAD

**Issue by user1121114685** [g1eny0ung/hugo-theme-dream#12]
比如我有一个项目在码云，他和本地图片的规律保持一致。我不需要重新编译url地址：
码云地址`https://gitee.com/xxxx/Blog`
本地图片地址 `/xxx/123.jpg`
同样 码云也有这个文件 `/xxx/123.jpg`
完整地址就是`https://gitee.com/xxxx/Blog/raw/master/xxx/123.jpg`
还请大佬指点指点 感谢！

**Comment by user1121114685** [comment]
请教下大佬，如何修改css js  字体的加载路径！

**Comment by g1eny0ung** [comment]
第一个没看懂，第二个字体我用的是`semantic-ui`的默认字体，你如果要改就自己改css文件去覆盖。

**Comment by user1121114685** [comment]
@g1eny0ung 谢谢大佬
