### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by lupa18** [g1eny0ung/hugo-theme-dream#123]
Is it possible to get links working in description (summary) at frontpage?

Also is it possible to link image's post to url's post in frontpage?

thanks!

**Comment by g1eny0ung** [comment]
Sorry for taking so long to reply.

The first question, do you mean the `motto` in the config?

And I didn’t understand the second question too much.

**Comment by lupa18** [comment]
No problem. 
1. I mean when you put a link in description. See number 1 at this image, should be a link but parses as plain text:

![20200619_01](https://user-images.githubusercontent.com/463429/85180166-1c02cb00-b259-11ea-92f9-82d8f8b893bb.png)

2. The other question is if its possible to link image to post link (see above image, number 2). When you click at thumb you should go to the post.

**Comment by g1eny0ung** [comment]
Know about it. Already done in f40b2d1.~

**Comment by lupa18** [comment]
Great ! many thanks !

About 2nd suggestion, I used a link in this format: 
`[Some text](https://www.example.com)`

and didn't work at main page (Yes it works at post page).

What format should I use?

thanks again!

**Comment by g1eny0ung** [comment]
Which "main" page do you use?

**Comment by lupa18** [comment]
I'm not sure what you mean. I think I use the default one.

**Comment by g1eny0ung** [comment]
The [text](url) is a markdown syntax. It can be only used in `.md` file. So I’m not sure which main page you are talking about.

**Comment by lupa18** [comment]
I use that link in test.md and that file, could show as a single page, were is renderized right (as link): 

![20200622_01](https://user-images.githubusercontent.com/463429/85326839-485e5780-b4a4-11ea-9a4f-64b00765b02d.png)

or at main page (front page), were is not renderized as link: 

![20200622_02](https://user-images.githubusercontent.com/463429/85326960-822f5e00-b4a4-11ea-881e-cccce1a3c13f.png)

Sorry if my explanation isn't clear enough.

**Comment by g1eny0ung** [comment]
Not mind.

![image](https://user-images.githubusercontent.com/15034155/85352762-48f4fd80-b539-11ea-9d30-856750ef71d5.png)

![image](https://user-images.githubusercontent.com/15034155/85352798-5c07cd80-b539-11ea-85c9-ecbcda2659bc.png)

I think the problem you encountered should be caused by the lack of `<!--more-->`.

Make sure `<!--more-->` behind your summary.

Here is the doc: https://gohugo.io/content-management/summaries/#manual-summary-splitting

**Comment by lupa18** [comment]
Perfect !! That works ! :green_heart:
