### ISSUE TITLE
Images won't appear

### ISSUE THREAD

**Issue by lewisl** [g1eny0ung/hugo-theme-dream#124]
I have images in the same directory as each posts index.md.
cover: front matter refers to the local image file.

They never appear.

**Comment by g1eny0ung** [comment]
You should put the images into the `static` folder.

**Comment by lewisl** [comment]
That’s unfortunate.

Why are you not reading the path provided?

This is a standard Hugo approach.

But, either can work.  Not sure I want to change the structure for just this theme.  Though in the future it is probably safer,

So, maybe.

Thanks for replying so quickly with answers that will work.

**Comment by g1eny0ung** [comment]
This feature can become true with a shortcode, maybe I will add it in the future (if I have some extra time).

And thx for using, I will continue to improve this theme.
