### ISSUE TITLE
Blog title

### ISSUE THREAD

**Issue by lewisl** [g1eny0ung/hugo-theme-dream#126]
You always use name's blog    as the title.

I found this and use .Parameters.title instead.

But, the change only appears on the home page.

When the navigator appears to the right, the blog name is changed.  I can;t find the layout.

I think you have some layout definitons embedded in your js.  You shouldn't do this.

**Comment by g1eny0ung** [comment]
https://github.com/g1eny0ung/hugo-theme-dream/blob/master/layouts/partials/header.html#L10

If you use the `.Params.Title` as the title, Hugo will read the context `.Title` (which define in each post) to render.

So, this behavior is normal.
