### ISSUE TITLE
Wrong Disqus sharing link (point to localhost)

### ISSUE THREAD

**Issue by thxred** [g1eny0ung/hugo-theme-dream#128]
After facebook window pops out its shows source as localhost instead of the correct domain.

**Comment by g1eny0ung** [comment]
This article solves the problems for me.

https://joejoomla.com/sound-off/167-what-to-do-when-your-disqus-comments-link-to-the-wrong-url.html

**Comment by g1eny0ung** [comment]
And also I found it's better to disable Disqus in development because it will upload the local URL to cover your real link.

**Comment by g1eny0ung** [comment]
> And also I found it's better to disable Disqus in development because it will upload the local URL to cover your real link.

A solution is to manually set `baseURL` in development:

```
hugo server -D --baseURL=https://your.site
```

**Comment by thxred** [comment]
Still getting the same results with, hugo server -D --baseURL=https://mysite. I'll try the other approach, disable Disqus in development, and seen if it works.

**Comment by thxred** [comment]
It works! And I was wrong. Using only "hugo server -D --baseURL=https://mysite", solved the problem.

**Comment by g1eny0ung** [comment]
@thxred Great! One drawback of this method is that all links‘ host within the site will change from localhost to baseURL during the development. This means that when the summary card is clicked, it will not jump to localhost, sometimes you need to type the post URL manually,

Although this is a flaw, I think it is acceptable.

I will close and still pin this issue to remind people who encounter such problems. Thx!
