### ISSUE TITLE
Creating continuous integration using Github to Firebase Deployment

### ISSUE THREAD

**Issue by leafarafael** [g1eny0ung/hugo-theme-dream#129]
Do you have any ideas how to create action workflow for this ?
I also connected my Github Repository to forestry.io

**Comment by g1eny0ung** [comment]
https://gohugo.io/hosting-and-deployment/hosting-on-firebase/#ci-setup I think this doc can help u.

Just install firebase ci and Hugo, run `hugo` to build the site, then follow the doc above to deploy it.
