### ISSUE TITLE
2 more questions: image and date

### ISSUE THREAD

**Issue by lupa18** [g1eny0ung/hugo-theme-dream#130]
Hello, 
1. Is it possible to show posts image at individual post view?

2. How can manage date format to fit language configuration? ie: Spanish date is different from English and I supposed is different to Chinese too. 

Thanks in advance !

**Comment by g1eny0ung** [comment]
1. This is possible, but I think adding the post image in the individual post page may interfere with the sight, especially when just entering.

2. Yep, we should handle the date format in different languages. I'm already pushing a commit 5f15a23 to execute it.

    But there have some jobs I need your help.

    You can click the commit link above, copy the `zh.toml` content, create a new file named `es.toml` (Spanish), and paste. Then replace the weekday and month with Spanish.

    Last, follow the `summary.html`'s change, add these codes:

    ```
    {{ if ... }}
    {{ else if eq .Site.Language.Lang "es" }}
      (Write Spanish date format here)
    {{ else }}
    ```

     Related doc: https://gohugo.io/content-management/multilingual/#customize-dates

**Comment by lupa18** [comment]
1. Can you make some highlights to get it working for our case? Maybe we can put an if "show_covers = true" condition?

2. I created data folder and put es.toml there. Then I put this in summary: 
```
  {{ if eq .Site.Language.Lang "es" }}
    {{ index .Site.Data.es.Weekday (printf "%d" .Date.Weekday) }}，{{ .Date.Day }} de {{ index .Site.Data.es.Month (printf "%d" .Date.Month) }} de {{ .Date.Year }}
  {{ else }}
    {{ .Date.Format "Monday, Jan 2, 2006" }}
  {{ end }}
```

but got this error:
```
Rebuild failed:

Failed to render pages: render of "home" failed: execute of template failed: template: index.html:14:9: executing "main" at <.Render>: error calling Render: failed to execute template ["summary"] v: "/usr/share/blog/themes/dream/layouts/_default/summary.html:21:7": execute of template failed: template: _default/summary.html:21:7: executing "_default/summary.html" at <index .Site.Data.es.Weekday (printf "%d" .Date.Weekday)>: error calling index: index of untyped nil
```

thanks !! :green_heart:

**Comment by g1eny0ung** [comment]
1. Ok, I can put a config to show the summary image in the single post page.

    ![image](https://user-images.githubusercontent.com/15034155/86382747-77ed3b00-bcc0-11ea-9fd8-134788a21155.png)

    Is your idea to put the image here?

2. Seems that you have weekday missing in the `es.toml`. You can give this repo a PR that I can help u to finish it,

**Comment by lupa18** [comment]
1. Yes ! then I also can move it .. but not sure how to link there. Also I'm not sure where to put featured images, now I'm putting at dream/static/img but I think should be outside dream folder. 

2. #131 :green_heart:

**Comment by g1eny0ung** [comment]
You can put your own images in `your blog/static/`. All static resources' path will relative to this folder.

**Comment by g1eny0ung** [comment]
@lupa18 I'm already finished the question 1. Here is the doc: https://g1eny0ung.site/hugo-theme-dream/#/params-configurations?id=showsummarycoverinpost-true

**Comment by lupa18** [comment]
Thanks !! here the result: https://antivirus.tedic.org/ ;)

**Comment by g1eny0ung** [comment]
Looks great!
