### ISSUE TITLE
can't evaluate field Resources in type *hugolib.Page

### ISSUE THREAD

**Issue by shrish83** [g1eny0ung/hugo-theme-dream#135]
This theme seems to be working great in my local development environment in Rstudio, but it generates some errors while deploying it to Netlify. I checked my code and it doesn't seem to have any error. All the error messages point to the [layouts/partials/back.html:3:29](https://github.com/shrish83/My-Blog/blob/master/themes/hugo-theme-dream/layouts/partials/back.html). 
I have also attached a screenshot of the complete errors as reported by netlify. 
[This is the link to my code](https://github.com/shrish83/My-Blog/tree/7b18a162a1291609fb9400aae0f9f33e030b0ecf)

![github issue](https://user-images.githubusercontent.com/58556695/87230176-998aa880-c3cb-11ea-8a65-8ce7f2bc57d5.png)

**Comment by g1eny0ung** [comment]
Seems that you need to put your `About me` into the about folder. For example, this is my blog structure:

![image](https://user-images.githubusercontent.com/15034155/87239800-bd8ad000-c445-11ea-8daa-2f0eb1159e59.png)

And don't forget to set the `about` folder to `Headless Bundle`. You can read the details in https://g1eny0ung.site/hugo-theme-dream/#/quick-start?id=add-quotabout-mequot

**Comment by shrish83** [comment]
Hey! Thank You.
I made the changes as mentioned by you and it worked just fine.
Also, I want to add a section of my favorite sites on the homepage like a "blogroll", and also I want to add a link to the RSS feed. But, I don't know exactly where should I do the changes and what should I write exactly. So, should I make changes in the layouts folder?

**Comment by g1eny0ung** [comment]
The markdowns in the about folder will not be rendered. it only uses in `back.html`, click flip button on the top left, and see them.

For "blogroll", you can put it anywhere, yep, if you wanna custom its position, just edit the HTML in the `layouts` folder.

I will update the theme later to support RSS feed, it's easy.

**Comment by shrish83** [comment]
Alright. Thank You for helping!

**Comment by g1eny0ung** [comment]
> Alright. Thank You for helping!
> But, exactly which file should change for "blogroll"?

Emmm...maybe you can edit the `header.html` to show your blogroll.

Or, I recommend u to put them in the about page (the back page), this is simple, just create a markdown by running: `hugo new about/blogroll.md` and put links to it.

Also the RSS feature, you can add `rss = true` in the config file, the related doc:

> https://g1eny0ung.site/hugo-theme-dream/#/params-configurations?id=rss-true

**Comment by shrish83** [comment]
Yes, I created a separate blogroll.Rmd file and it worked just fine. Also the Rss link works now. 
But, Is there any way I can show my complete content of my posts in the RSS feed instead of just the description?

**Comment by g1eny0ung** [comment]
I think this tutorial can help you: https://www.godo.dev/tutorials/hugo-full-text-rss/

**Comment by shrish83** [comment]
Thank You! It all worked out.
