### ISSUE TITLE
支持备案设置吗

### ISSUE THREAD

**Issue by How-invin** [g1eny0ung/hugo-theme-dream#139]
这款主题是我在hugo上找到最中意的一款，想当nice。
可是有一个问题现在正在困扰我，我发现并没有像多数hexo主题一样，有设置备案的选项。这对部署在国内服务器造成了困惑。

**Comment by How-invin** [comment]
找到的暂时方法：
partial/header上修改

```
<section class="ui bottom attached center aligned segment">
    {{ if .Site.Params.siteStartYear }}
      <p>© {{ if eq now.Year .Site.Params.siteStartYear }}{{ now.Year }}{{ else }}{{ .Site.Params.siteStartYear }} - {{ now.Year }}{{ end }} {{ .Site.Title }}</p>
    {{ else }}
      <p>© {{ now.Year }} {{ .Site.Title }}</p>
 
    {{ end }}

	<a href="{{ .Site.Params.BeianURL }}" target="_blank" >{{ .Site.Params.BeianTXT }}</a>
    <p>Powered by <a href="https://gohugo.io/" target="_blank">Hugo</a> with theme <a href="https://github.com/g1eny0ung/hugo-theme-dream" target="_blank">Dream</a>.</p>
  </section>
</article>
```
![Screen Capture_select-area_20200801172541](https://user-images.githubusercontent.com/41119059/89098671-31ecd980-d41c-11ea-9240-25c9f11222a7.png)

**Comment by g1eny0ung** [comment]
我可以在 header 的底部（也就是你修改的这个位置提供一个可插入文本的设置），比如 `headerBottomText = ""`。

**Comment by g1eny0ung** [comment]
![image](https://user-images.githubusercontent.com/15034155/89099022-fa336100-d41e-11ea-9e3d-4f8d0338823c.png)

像这样，通过设置 `headerBottomText = "<a>苏ICP备xxxxxx</a>"`

**Comment by How-invin** [comment]
嗯，赞同。
再有一个想法是，如果可以在选择文章背景图片就更好了。一个好看的背景在pc端上的效果改善还是显而易见的。

**Comment by g1eny0ung** [comment]
`headerBottomText` 已添加，文章背景是个好点子 👍🏽，我看看后面怎么做一下。
