### ISSUE TITLE
Netlify CMS

### ISSUE THREAD

**Issue by stephenajulu** [g1eny0ung/hugo-theme-dream#142]
Hi, how are you?
This theme is great.
Could you kindly add Netlify CMS?
It would really help with workflow.
I am an avid blogger and would love to move from wordpress to jamstack and use this theme.

**Comment by g1eny0ung** [comment]
Is this what you mean? https://www.netlifycms.org/

I will learn how to deploy this in these two days.

**Comment by g1eny0ung** [comment]
https://g1eny0ung.site/hugo-theme-dream/#/netlify-cms finished.
