### ISSUE TITLE
Cover images don't show in single post view.

### ISSUE THREAD

**Issue by Sp-cy** [g1eny0ung/hugo-theme-dream#150]
The update broke something in the single post view.

**Comment by g1eny0ung** [comment]
I didn't modify the relevant code. Did you set this? https://g1eny0ung.site/hugo-theme-dream/#/params-configurations?id=showsummarycoverinpost-true

**Comment by Sp-cy** [comment]
Yes, that has been set. I returned to the past version of the single html and it's ok but the current file didn't work for me. I'll test again and report back.

**Comment by g1eny0ung** [comment]
> Yes, that has been set. I returned to the past version of the single html and it's ok but the current file didn't work for me. I'll test again and report back.

👌🏼
