### ISSUE TITLE
切换主题时同时切换背景 以及关于暗色主题的一些小问题

### ISSUE THREAD

**Issue by WingsZeng** [g1eny0ung/hugo-theme-dream#152]
您好！

我很喜欢您的主题，尤其是亮色暗色主题切换，太炫酷了。

在使用您的主题的过程中，我产生了这样一个想法：在切换主题时同时切换背景。

我比较喜欢暗色主题，一直用的是暗色，背景图片也是根据暗色主题来配的。但是当我切换到亮色（或者用另一个设备第一次打开博客）的时候，亮色的主题和我设置的背景并不搭配。

还有几个小问题
1. 如何设置初始的主题配色为暗色？第一次打开博客的时候默认是亮色的
2. 暗色下Markdown的表格颜色能否修改？表格是灰白色的，和暗色的主题不太搭配

由于我对前端知识以及Hugo知之甚少，自己并不能很好的解决这些问题，还烦请您帮忙。

祝：
身体健康！万事如意！

**Comment by g1eny0ung** [comment]
> 在使用您的主题的过程中，我产生了这样一个想法：在切换主题时同时切换背景。

这个是可以做到的，之前也想过，忘了做了，一会儿加上。

> 如何设置初始的主题配色为暗色？第一次打开博客的时候默认是亮色的

这个切换过一次暗色主题就会调用浏览器 API 存储当前主题，下一次打开就会是暗色的了

> 暗色下Markdown的表格颜色能否修改？表格是灰白色的，和暗色的主题不太搭配

这个是样式问题，我测一下。

**Comment by WingsZeng** [comment]
谢谢大佬
支持大佬

**Comment by g1eny0ung** [comment]
@WingsZeng Finished. https://g1eny0ung.site/hugo-theme-dream/#/dark-mode
