### ISSUE TITLE
Fully support tags with Capital letters and spaces

### ISSUE THREAD

**Issue by grokify** [g1eny0ung/hugo-theme-dream#154]
Tags with Capital letters and spaces partially work now:

One post pages, they work as desired:

* Displays with desired capitals and spaces on post pages
* Links correctly to lowercase / hyphen URLs

In header bock and `/tags` page, display is also lower-case with hypens:

* header tag block
* `/tags` page

From looking at `layouts/partials/header.html` it seems like it's designed to work as the URL includes `{{ $name | urlize }}` but the link `title` and `innerHtml` are simply `{{ $name }}`. It looks like the tag has already been urlized before being added to `Site.Taxonomies`. Removing this looks like it should work.

It looks like they display correctly on posts pages because posts is reading them from the post without modification, but the header is reading them from a processed `Site.Taxonomies` list.

I still getting up to speed on Hugo. Is this something this theme can resolve or is this a Hugo level issue?

### `layouts/_default/single.html` - displays correctly

* `{{ $tag }}` shows upper case and spaces as desired
* `{{ $tag | urlize }}` uses lower case with hyphens as desired

```html
    <footer class="ui attached segment dream-tags" data-html2canvas-ignore>
      {{ if isset .Params "tags" }}
        {{ range $tag := .Params.tags }}
          <a class="ui label" href="{{ "tags/" | relLangURL }}{{ $tag | urlize }}" title="{{ $tag }}">{{ $tag }}</a>
        {{ end }}
      {{ else }}
          <a class="ui label">{{ i18n "noTag" }}</a>
      {{ end }}
      <div
        class="ui label"
        style="float: right; cursor: pointer;"
        onclick="savePostAsImg()">
        <i class="save icon"></i>{{ i18n "saveAsImage" }}
      </div>
    </footer>
```

### `layouts/partials/header.html` - displays with "URL slugs"

* `{{ $name }}` uses lower case with hyphens - would like to change this to original tag name with upper case and spaces
* `{{ $name | urlize }}` uses lower case with hyphens as desired

```html
  {{ if .Site.Taxonomies.tags }}
  <section class="ui attached center aligned segment dream-tags">
    {{ range $name, $taxonomy := .Site.Taxonomies.tags }}
      <a class="ui label" href="{{ "tags/" | relLangURL }}{{ $name | urlize }}" title="{{ $name }}">{{ $name }}</a>
    {{ end }}
  </section>
  {{ end }}
```

**Comment by g1eny0ung** [comment]
> I still getting up to speed on Hugo. Is this something this theme can resolve or is this a Hugo level issue?

After searching, the official docs don't describe how to normalize the tag name. But I found a link in Hugo Discourse with the same problem: https://discourse.gohugo.io/t/taxonomy-name-in-site-taxonomes/5531.

I think this solution can solve this issue and I already commit it in e06ac94.
