### ISSUE TITLE
about description

### ISSUE THREAD

**Issue by walkureHHH** [g1eny0ung/hugo-theme-dream#155]
I set the decription in config.toml but I can't find description display in the website. What the meaning of the description? And how it be used?
![2020-11-14 22-07-27屏幕截图](https://user-images.githubusercontent.com/60261171/99149012-5cf6f280-26c6-11eb-8184-1ed4d03cd3c8.png)
![2020-11-14 22-07-59屏幕截图](https://user-images.githubusercontent.com/60261171/99149014-5ff1e300-26c6-11eb-8ce7-e5d9eaa555d1.png)

**Comment by g1eny0ung** [comment]
The description will be used as metadata. Usually, only search engines will use it to index your site.

![image](https://user-images.githubusercontent.com/15034155/99149076-dd1d5800-26c6-11eb-946e-86b8baa9c92a.png)

**Comment by walkureHHH** [comment]
> The description will be used as metadata. Usually, only search engines will use it to index your site.
> 
> ![image](https://user-images.githubusercontent.com/15034155/99149076-dd1d5800-26c6-11eb-946e-86b8baa9c92a.png)

OK, thank you!
