### ISSUE TITLE
How to set cover image for each article

### ISSUE THREAD

**Issue by walkureHHH** [g1eny0ung/hugo-theme-dream#156]
Excuse me, it is possible to set cover image for each articles rather than randomly using the default1-4.jpg? If if possible, how should I set it?

By the way, I really like the theme, thank you for creating it!

**Comment by g1eny0ung** [comment]
Definitely can. Just edit the `cover` field to customize it.

![image](https://user-images.githubusercontent.com/15034155/99182063-9898c780-276d-11eb-8ba0-e1e8bfafd211.png)

And thx for loving it.~ ❤️

**Comment by walkureHHH** [comment]
> Definitely can. Just edit the `cover` field to customize it.
> 
> ![image](https://user-images.githubusercontent.com/15034155/99182063-9898c780-276d-11eb-8ba0-e1e8bfafd211.png)
> 
> And thx for loving it.~

Thank you, I do it. By the way, what is the meaning of the images field, and where I can find the explaination of all fields at the top of .md files? I can't find it in hugo official doc.

**Comment by g1eny0ung** [comment]
You can find all definitions there: https://gohugo.io/content-management/front-matter/.

**Comment by walkureHHH** [comment]
> You can find all definitions there: https://gohugo.io/content-management/front-matter/.

Thanks!
