### ISSUE TITLE
Image path mistake in some categories page

### ISSUE THREAD

**Issue by walkureHHH** [g1eny0ung/hugo-theme-dream#157]
I meet a strange problem
When I am in home page, all cover image are display correctly.
![dream1](https://user-images.githubusercontent.com/60261171/99266298-94e46e00-285d-11eb-8073-ce6fc155a99a.PNG)
When I am in the Page of category "english studying", cover image is right too.
![dream2](https://user-images.githubusercontent.com/60261171/99266483-c6f5d000-285d-11eb-8508-5cd2fb1434d9.PNG)
But when I am in the page of category "markup", the path of cover image is wrong and can't display, It seems the baseurl become to https://walkurehhh.gitee.io/categories/markup/
![dream3](https://user-images.githubusercontent.com/60261171/99266759-163c0080-285e-11eb-837f-2042f22ea4a3.PNG)
How to solve it?

**Comment by g1eny0ung** [comment]
Make sure the image path is relative to the root of the site (with a `/` prefix). For example, `img/Augmented_matrix.png` to `/img/Augmented_matrix.png`.

**Comment by walkureHHH** [comment]
> Make sure the image path is relative to the root of the site (with a `/` prefix). For example, `img/Augmented_matrix.png` to `/img/Augmented_matrix.png`.

That is right, I miss the / at the begining. Thank you very much!
