### ISSUE TITLE
The license icon is displayed as a box

### ISSUE THREAD

**Issue by RangerNJU** [g1eny0ung/hugo-theme-dream#158]
主题做得很漂亮很独特，文档也非常详细:)
鼓励，支持！

提一个小问题，访问[主页](https://g1eny0ung.site/)并翻页后，截图中左上角的icon似乎不能正常加载。我对前端知识不太熟悉，请问想让它正常显示图标的话，是需要设置proxy还是用其他方法显示本地图片？

![screenshot_20201122_140447](https://user-images.githubusercontent.com/71978856/99896469-2e83a380-2cd4-11eb-853e-803cc3a6403c.png)

**Comment by g1eny0ung** [comment]
感谢支持 😄。这个应该是图片链接被墙了。

**Comment by RangerNJU** [comment]
已经解决，记录一下需要修改的地方，给后来人指路：

0. 到外链上下载图片（我命名为CCBYNCSA.png）后放到img文件夹下
1. 在config.toml中找到copyright开头的一行
2. 将其中的img标签中的src属性对应的字符串改成`src="/img/CCBYNCSA.png"`

改好后的copyright一行长成这个样子：
`copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="/img/CCBYNCSA.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'`，如果本地运行`hugo serve`后发现依然无法正常显示，可以考虑在浏览器中按F12或鼠标右键->Inspect来观察网页元素，确定是什么地方不符合预期。
