### ISSUE TITLE
Feature request: sticky TOC

### ISSUE THREAD

**Issue by RangerNJU** [g1eny0ung/hugo-theme-dream#159]
根据[这里](https://gohugo.io/content-management/toc/)的指导可以自动生成文章开始时的TOC。进一步地想实现读者[滚动时TOC一直保持在文章一侧的效果](https://ma.ttias.be/adding-a-sticky-table-of-contents-in-hugo-to-posts/)。

作为前端小白，后面这篇文章里提到的代码就不知道要放到哪个文件里了，迫不得已再发一个Feature request。

**Comment by g1eny0ung** [comment]
这个需要放在 `layouts/_default/single.html` 里，但是目前没有支持这个功能，我后面加一下。

**Comment by g1eny0ung** [comment]
@RangerNJU Already done in 646dbafa0c05673eb5f0ccb6a54b0427261be6b3 and eacbcc3f3625ce3bd770d55f130da915fa1f7ff0.

**Comment by RangerNJU** [comment]
Well done :smile:
