### ISSUE TITLE
Response speed very slowly, even has 1280ms!!!!

### ISSUE THREAD

**Issue by LiuShaoYe-173** [g1eny0ung/hugo-theme-dream#164]

**Comment by LiuShaoYe-173** [comment]
Hugo-MDL : 9.3s (avg)
hugo-theme-dream : 10s (avg)

**Comment by g1eny0ung** [comment]
Due to the masonry layout used, It does affect the loading speed of the entire page.

Here are some optimization suggestions I can give:

1. Try to use **compressed png** pictures.
2. Use global CDN to speed your site, like Cloudflare.

**Comment by g1eny0ung** [comment]
3. Use `hugo --cleanDestinationDir --minify --gc` to compress the production files.
