### ISSUE TITLE
默认暗色主题以及固定toc问题

### ISSUE THREAD

**Issue by WingsZeng** [g1eny0ung/hugo-theme-dream#165]
您好!
我十分喜爱您的主题. 在使用的过程中, 我遇到了一些问题.
1. 请问有没有能够设置默认主题就是暗色的方法? 我直接尝试修改js的isDark="y", 但是这样会出现许多其他问题.
2. 由于我的head比较"长", toc在head最底部, 无法全部显示. 在滚动的页面的时候head固定住了, 这样toc依旧无法全部显示. 请问能否在toc部分滚动到顶端之后把toc固定住?

**Comment by g1eny0ung** [comment]
第一个我在 8e94a4a 中解决了，设置一下 `defaultDark = true` 即可。

文档：https://g1eny0ung.site/hugo-theme-dream/#/params-configurations?id=defaultdark-true.

第二个问题可以描述的更清晰一点嘛？没太看懂。

**Comment by WingsZeng** [comment]
不好意思表述不清, 描述里的head有误, 应该是header, 就是侧边栏. toc在侧边栏上方, 滚动页面toc固定住了, 但是侧边栏也固定住了, 导致侧边栏信息无法完全显示. 我尝试把toc放在header下方, 但是失败了, 这样整个侧边栏都固定住了. 能否做到像[Hexo-NexT](https://github.com/theme-next/hexo-theme-next)主题这样的效果, 将toc放在侧边栏的底部, 滚动到toc的时候固定住.

**Comment by g1eny0ung** [comment]
已修复，我给 toc 的父元素加上了 `height: 100%`，这样即便 toc 很长，滚动到最底部也可以正常显示 header 了。

**Comment by WingsZeng** [comment]
感谢♥
