### ISSUE TITLE
Can not scroll in Chrome/Chromium desktop

### ISSUE THREAD

**Issue by techmagus** [g1eny0ung/hugo-theme-dream#169]
Issue: Scrolling is working when viewing the theme in Chrome/Chromium desktop. It works fine under Firefox 85.0.

OS: Ubuntu 20.04 LTS
Browser: Chromium Version 89.0.4385.0

Sites tested:

* Demo site - https://themes.gohugo.io/theme/hugo-theme-dream/
* Your site - https://g1eny0ung.site
* Offline test site

-- side note: I opened an issue in the wrong repo (your site's repo), I closed that one and created a new one here. Apologies!

**Comment by g1eny0ung** [comment]
> I opened an issue in the wrong repo (your site's repo), I closed that one and created a new one here. Apologies!

Never mind. 🤣

Maybe this issue is related to https://github.com/KingSora/OverlayScrollbars because the dream theme uses it to unify the scrollbar style in different platforms.

I will try to find out if there is the same situation.

**Comment by Darthagnon** [comment]
@techmagus I noticed scrolling was a bit broken on your website, though I haven't noticed the same on mine or g1eny0ung's. I do suspect it is the overlay scrollbars js; iirc, I added a switch to disable it in the active fork.

**Comment by g1eny0ung** [comment]
In v3, I've not used OverlayScrollbars. And I'm no longer going to maintain the previous major version. So I'll close this issue.
