### ISSUE TITLE
Missing base URL in tag and category links

### ISSUE THREAD

**Issue by techmagus** [g1eny0ung/hugo-theme-dream#170]
In the loop for tags and categories in layouts/partials/header.html the base URL is missing when the URL is generated.

Example:
* base URL is: domain.tld/web/
* post URL is: domain.tld/web/posts/new-post

* Tag link generated is: domain.tld/tags/tag01 -- it should be domain.tld/web/tags/tag01
* Cat link generated is: domain.tld/categories/cat01 -- it should be domain.tld/web/categories/cat01

I tried adding ```relLangURL```, ```relURL```, ```absLangURL```, and ```absURL``` but I'm doing something wrong ^^:;

Thank you

**Comment by g1eny0ung** [comment]
Should be fixed in e695204.

**Comment by techmagus** [comment]
Ahh, so that's how it's done. I was definitely doing it wrong. 🤣

Thank you very much!!
