### ISSUE TITLE
[v2-beta] The .dream-header class in /scss/ is still from v1.x

### ISSUE THREAD

**Issue by techmagus** [g1eny0ung/hugo-theme-dream#172]
Hi,

The scss entry for the .dream-header class is still from v1.x
```
    max-width: 512px;
    margin-left: 2rem;
```

Instead of the v2:
```
    display: flex;
    justify-content: center;
    align-items: center;
```

But the /static/css/site.css is updated and can be used directly.

Shalom!

**Comment by g1eny0ung** [comment]
I don't understand what you mean too much.

**Comment by techmagus** [comment]
No worries. ^_^

In /hugo-theme-dream/src/sass/site.scss the .dream-header class is still set to:
```
max-width: 512px;
margin-left: 2rem;
```

So when generating the site, the header in v2 is on the left side and the information is below the avatar (like how it was in v1).

But if I use /hugo-theme-dream/static/css/site.css (I copied the file to my own /static/css/ folder) the new header in v2 is displayed correctly.
```
display: flex;
justify-content: center;
align-items: center;
```

I'm not sure what else are different from the site.scss and site.css files

**Comment by g1eny0ung** [comment]
😆 Know about it. The `site.css` is generated from `site.scss`. You only need to edit the `site.scss` if you want to change something. After editing, just run `npm run prod` or `yarn prod` in the theme dir. This command will compile the `scss` files to `css`.

**Comment by techmagus** [comment]
Ahh! Got it.

Thank you. :)
