### ISSUE TITLE
thank you for the new design i hope it will look like yours, you know? rounded corners, softer colors. they are quite different.

### ISSUE THREAD

**Issue by owlsecco** [g1eny0ung/hugo-theme-dream#174]
feel free to close this. just putting it here, hoping you'll implement some features yours has

**Comment by g1eny0ung** [comment]
It's easy to come true! You can refer to the custom CSS file from my blog.

https://github.com/g1eny0ung/blog/blob/master/static/css/custom.css

**Comment by owlsecco** [comment]
thank you
