### ISSUE TITLE
Quick question!

### ISSUE THREAD

**Issue by 33nano** [g1eny0ung/hugo-theme-dream#176]
It'll be much easier to ask, but here goes, 2 questions.

1. How do i set an image background for my posts?
2. How do i disable the image background cycling or changing every time i refresh my site?

**Comment by 33nano** [comment]
My bad, just figured it out. I did a __Ctrl + F__ through the code for a _.jpg_ extension. I found the line `<img src="/img/default{{ index (shuffle (seq 1 4)) 0 }}.png" alt="{{ .Title }}" />`

**Comment by g1eny0ung** [comment]
Never mind. The shuffle function is just for exhibit the demo site (https://themes.gohugo.io/theme/hugo-theme-dream/).

**Comment by 33nano** [comment]
@g1eny0ung Noted
