### ISSUE TITLE
change the positions of the post's page

### ISSUE THREAD

**Issue by vutruong99** [g1eny0ung/hugo-theme-dream#178]
Hey bro. I was wondering if there is a way to switch the post's content to the right and the navigation + share to the left of the page like so? :

![image](https://user-images.githubusercontent.com/43692044/108670097-dd708f00-7510-11eb-89de-f09285621438.png)

I tried changing the direction of the flex-container to row-reverse, but that will create a conflict with the HOME page since the posts are arranged by date. I figure that changing the order of the element may work, but I guess there is no way to adjust the HTML files.

**Comment by g1eny0ung** [comment]
I added a class for the grid container in b3a37fe.

Now it will be very easy to implement, add the below content to your custom CSS:

```css
.ui.grid.dream-grid-single {
  flex-direction: row-reverse;
}
```

**Comment by vutruong99** [comment]
> 
> 
> I added a class for the grid container in [b3a37fe](https://github.com/g1eny0ung/hugo-theme-dream/commit/b3a37fe7c1777eb4faa98fa7e4aea997fffe110b).
> 
> Now it will be very easy to implement, add the below content to your custom CSS:
> 
> ```css
> .ui.grid.dream-grid-single {
>   flex-direction: row-reverse;
> }
> ```

Hi bro, as I said that will work BUT will create a small glitch when loading the Home page. It will be `row-reverse` first, and then **snap back** to normal because the posts are arranged by date. I'm not sure if I had explained it clearly :(

**Comment by g1eny0ung** [comment]
@vutruong99 I saw your deleted comment in my mail notifications. I realized this problem, and now I write it as a configurable param `reversePostAndAside`, simply add this into your `config.toml`:

```toml
[params]
  reversePostAndAside = true
```

Ref: https://g1eny0ung.site/hugo-theme-dream/#/params-configurations?id=reversepostandaside-true

**Comment by vutruong99** [comment]
Oh haha, I deleted it because I think I have not updated your latest theme. Thanks so much for your help, I am now trying to update your theme and try the Params. I will close this as soon as I finish :D
