### ISSUE TITLE
How do you add icons for custom social links?

### ISSUE THREAD

**Issue by 33nano** [g1eny0ung/hugo-theme-dream#179]
I looked at the structure of the links outlined in the socials.html and i added gamejolt as one of the custom links. I updated my config.toml file to reflect the changes made. Upon reloading my website, the link is definitely there when i hover my mouse over the blank area of the social links. There is no icon available whatsoever. 

I am still working on it, but you can preview the site [here](https://33nano.netlify.app/)

**Comment by g1eny0ung** [comment]
This is because I'm only using the icon set from https://semantic-ui.com/elements/icon.html#brands. Currently, this theme doesn't support the feature of add custom icons in socials.

I will try to implement this feature in several few days.

**Comment by 33nano** [comment]
That's great news. I just realized i can add markdown badges, so I'm planning to do that instead.  Its still awesome, that you are planning to add the feature in a few days.
