### ISSUE TITLE
Preserve tag case

### ISSUE THREAD

**Issue by rakovskij-stanislav** [g1eny0ung/hugo-theme-dream#182]
Hello. Some of tags I have in CamelCase (e.g. `PyInstaller`), some of them as splitted words (e.g. `PyCharm Community`), some of them  as uppercased word (`CTF`, `IDA`), and the last one mixed (`CnC`). Do you have any config option to preserve the case used in posts?

**Comment by g1eny0ung** [comment]
Should be resolved in 97138afd4fba31e19bc17381cd5276f16a4c7542. Please have a try.

**Comment by rakovskij-stanislav** [comment]
Have ported this changes to old version of Dream (1.5.0). Now at least I have lowercased tags everywhere, thanks)

**Comment by g1eny0ung** [comment]
> Have ported this changes to old version of Dream (1.5.0). Now at least I have lowercased tags everywhere, thanks)

Already cherry-pick changes into the `release-1.6` branch.
