### ISSUE TITLE
Can't see commands.

### ISSUE THREAD

**Issue by RedsonBr140** [g1eny0ung/hugo-theme-dream#186]
Hi, I'm trying to adapt my blog to the theme of dreams, but the code area in the markdown is full of bugs, I'm using the dark theme, switching to the white theme works well. See for yourself:
![image](https://user-images.githubusercontent.com/61910521/114287920-8cc1e080-9a41-11eb-820f-c1cea494e092.png)
![image](https://user-images.githubusercontent.com/61910521/114287943-b1b65380-9a41-11eb-8714-2f5118c83432.png)
https://cafecomterminal.cf/posts/drivers-nvidia-freebsd/

Code [here](https://gitlab.com/cafecomterminal/cftsite)

**Comment by g1eny0ung** [comment]
Try to set the `highlightjsThemeDark` to improve it.

Ref: https://g1eny0ung.site/hugo-theme-dream/#/highlightjs.

**Comment by RedsonBr140** [comment]
Thank you :smile:. I would also like to thank you for the support, and for the creation of this beautiful theme: D.
