### ISSUE TITLE
保存本地、推特、脸书的窗口被改变了/po文的界面大小有变化

### ISSUE THREAD

**Issue by cyclonege** [g1eny0ung/hugo-theme-dream#188]
第一张是before
<img width="1125" alt="Screen Shot 2021-04-19 at 15 36 37" src="https://user-images.githubusercontent.com/82311549/115192130-59f4a800-a125-11eb-967a-417269fa79ca.png">
第二张是after the tag changes...
<img width="1171" alt="Screen Shot 2021-04-19 at 15 36 47" src="https://user-images.githubusercontent.com/82311549/115192148-5f51f280-a125-11eb-81b1-e5f974fbb6bb.png">

**Comment by cyclonege** [comment]
@g1eny0ung

**Comment by g1eny0ung** [comment]
Already done.

**Comment by cyclonege** [comment]
Thank you!!
