### ISSUE TITLE
使用dream主题，本地预览正常，部署到github页面样式效果丢失

### ISSUE THREAD

**Issue by kuole-o** [g1eny0ung/hugo-theme-dream#194]
使用这个主题，我已经css js都排查看过了，正常加载，但网页还是主题效果不对，麻烦帮忙指点：https://kuole-o.github.io/

**Comment by g1eny0ung** [comment]
看起来 `baseURL` 设置的有问题，需要设置为 `https://kuole-o.github.io`。
