### ISSUE TITLE
所有文章的disqus评论都是一样的

### ISSUE THREAD

**Issue by doorOfChoice** [g1eny0ung/hugo-theme-dream#2]
hello 题主, 很喜欢你的主题。
不过在配置disqus的时候出了一点问题.
你的single.html里面写了discus提供的脚本，然后我就只在config.toml里面配置了disqusShortname。
但是每次提交在disqus上产生的标题都是同一个，以至于每篇文章的评论都是一样的。
请教一下题主解决方案😄

**Comment by g1eny0ung** [comment]
🤣 感谢提出这个问题啊，好致命的问题。。现在已经修复了～

出现这个bug的原因是，由于页面是分为两部分的，front和back，front就是页面的主体，back则是相当于about页面，通过左上角的翻转按钮来展现。

但是当页面是文章页面，也就是url路径是post/something的时候，就会出现两个disqus评论区域，导致设置为了同一disqus thread，也就是back的disqus的设置生效了，所以出现了无论在哪里评论都是相同的评论。。

如果你那边还是出现问题，再联系我 👌 ，我会及时帮你解决的。

**Comment by doorOfChoice** [comment]
问题已经解决，谢谢题主，希望写出更多优质主题~😄
