### ISSUE TITLE
CSS customization issues

### ISSUE THREAD

**Issue by santiyounger** [g1eny0ung/hugo-theme-dream#200]
Hey thanks for the awesome theme.

I'm stuck trying to modify some of the css. but I can't get it to work.

I created the `custom.css` file [as shown in the docs](https://g1eny0ung.site/hugo-theme-dream/#/params-configurations)
in this path

`/static/css/custom.css`

I'm trying to change the font size in a blog, as well as the margins, padding, and similar simply things.

I've tried to achieve this in the new `v2.0.0` beta, as well as the current one that one gets when doing `git clone https://github.com/g1eny0ung/hugo-theme-dream.git dream` 

Thanks a lot, super excited for the stable  `v2.0.0`, keep up the excellent work

**Comment by santiyounger** [comment]
I found out why it wasn't working. In case anyone else runs into this issue.

in the `config.toml` I needed to uncoment

```toml
  # [params.advanced]
  #   customCSS = ["css/custom.css"]
```

so that it looks like this
```toml
  [params.advanced]
    customCSS = ["css/custom.css"]
```

That lets the `custom.css` file work

This was definitely my bad, I don't know why I missed that

**Comment by g1eny0ung** [comment]
I'm glad you like it.
