### ISSUE TITLE
老哥，请问自己加的内容，怎样适配dream的夜间模式

### ISSUE THREAD

**Issue by kuole-o** [g1eny0ung/hugo-theme-dream#204]
夜间模式现在切换，会闪一次才会变，有计划重构或优化夜间模式吗

我自己加的内容，怎样判断开了夜间模式，然后css改一个颜色呢？

dream好像引用了一个什么ui，都是预设的？很多div或class名称都很奇怪，也无法查到对应的css指令是哪个，无从下手去改啊 😭😭

我接了个twikoo评论系统，太好用了 建议可以加到dream里了。

以上请有空看到帮忙解答下…guole.fun这里，可以查看开启夜间模式后的文章页一些问题。不胜感激🙏

以及面包屑导航条的颜色问题…自己改了没用😰

**Comment by g1eny0ung** [comment]
夜间模式的代码在这里：https://github.com/g1eny0ung/hugo-theme-dream/blob/master/src/js/theme.js。

基本全是复用的 `.ui.inverted`，这是 semantic-ui 默认的暗色显示。如果想自己改的话，只能按照我的博客自定义的那样，覆盖 `.ui.inverted` 样式。

所以总体的流程是这样的：如果新添加了一部分内容，就需要再 `theme.js` 中添加相应的 theme 修改函数（如果存在非默认暗色显示的样式，需要额外写 JS 手动增加删除。），然后通过 `yarn prod` 编译生效。

**Comment by kuole-o** [comment]
收到。无数个时刻都想给你提需求（互联网打工人的潜意识） 😂😂  
  
还是希望，增加个文章底部有个 “上一篇”“下一篇”的链接，帮助读者浏览完后，去其他内容。我从木木木那边，借鉴到相关代码，无奈样式整半天没改过来   
```
 <div class="Upper-and-lower">
      {{ if .NextInSection }}
        <a href="{{ .NextInSection.Permalink }}">{{ .NextInSection.Title }}</a>
      {{ end }}
      {{ if .PrevInSection }}
        <a href="{{ .PrevInSection.Permalink }}">{{ .PrevInSection.Title }}</a>
      {{ end }}
    </div>
```
  
以及面包屑导航：  
```
<div  class="breadcrumb">
    {{ template "breadcrumbnav" (dict "p1" . "p2" .) }}
  </div>
  {{ define "breadcrumbnav" }}
  {{ if .p1.Parent }}
    {{ template "breadcrumbnav" (dict "p1" .p1.Parent "p2" .p2 )  }}
  {{ else if not .p1.IsHome }}
    {{ template "breadcrumbnav" (dict "p1" .p1.Site.Home "p2" .p2 )  }}
  {{ end }}
  <li{{ if eq .p1 .p2 }} class="active"{{ end }}>
    <a href="{{ .p1.Permalink }}">{{ .p1.Title }}</a>
  </li>
  {{ end }}
```
  
还有这个bber功能，类似以前空间的“说说”？可以自言自语  
https://immmmm.com/bb-by-wechat-pro/#%e9%99%84%e8%b5%a02-bber-weixin  
  
还想页面有个一键到顶部的按钮，可以是个小导航栏，整合夜间模式、一键回到顶部、直达评论区这些功能  
  
以及Markdown里，插入图片支持居中布局  
https://migchar.com/hugo-formation-common-implementation/  
  
加点新功能吧，老板  孩子都馋哭了 😂😂😂😂

**Comment by g1eny0ung** [comment]
有时间再慢慢加 🤣，日常实在太忙。
