### ISSUE TITLE
[Firefox] The TOC of the post page cant be sticky

### ISSUE THREAD

**Issue by remylavergne** [g1eny0ung/hugo-theme-dream#210]
Hi 👋 

First, thank you very much for this theme!

I use Firefox as my daily browser. And, I realized that there was a problem with the clickable area for navigation links (left side of a post). This is the blue area in the screenshot.

![Screenshot 2021-05-26 at 14 49 04](https://user-images.githubusercontent.com/28859882/119664543-ba1cef00-be33-11eb-8a23-a34127cab02b.png)

<img width="788" alt="image" src="https://user-images.githubusercontent.com/28859882/119664711-e6387000-be33-11eb-8542-0b7f6eb2cd6a.png">

To reproduce: <https://remylavergne.dev/posts/go-hugo-auto-github-deploy/>

Possible way: the `TableOfContents` has a "margin top" on Firefox.

Thank you :)

**Comment by g1eny0ung** [comment]
After debugging, this related to `position: sticky`. Seems Firefox doesn't support it very well, so I disable it temporarily in 8c25e47e4214570747f190590430ea3ace2cf4b6.

**Comment by remylavergne** [comment]
It works! Thank you very much. I tried to fix it but CSS / HTML isn't my domain 😅
