### ISSUE TITLE
切换灯光模式时 scrollToTop.js 的一个bug

### ISSUE THREAD

**Issue by kuole-o** [g1eny0ung/hugo-theme-dream#215]
我在最近两天，启用了 dream release 2.0.0beta1 版本。我发现，首次进入页面后，此时一键回到顶部的top按钮，颜色是正常的。  
  
当我点击切换一次灯光模式，换成暗色，停留在暗色模式时，再切换到另外一个页面，此时 已然是暗色模式，但这个 top按钮，似乎自己又切了一次颜色？从白色变成了黑色，导致暗色模式下，黑色看不清。  
  
同样的方法，切换到暗色，再切换成日光模式，再点击一个页面，此时top按钮又持续是白色，与背景色一致不易查看。  
  
以上，希望能解决下。放上配图：  
![S10603-21412435(1).png](https://user-images.githubusercontent.com/63436555/120656272-10360600-c4b6-11eb-94cd-dbfc0eafcae9.png)
![S10603-21414945(1).png](https://user-images.githubusercontent.com/63436555/120656284-12986000-c4b6-11eb-8834-67e435001d02.png)
![S10603-21441357(1).png](https://user-images.githubusercontent.com/63436555/120656300-162be700-c4b6-11eb-869d-932ec6aa40a1.png)

**Comment by g1eny0ung** [comment]
在 cd43584fa594586594a90aec00a3df0c43cccb10 已修复，感谢指出。
