### ISSUE TITLE
Pages in the Header

### ISSUE THREAD

**Issue by PetiPandaRou** [g1eny0ung/hugo-theme-dream#216]
It should be great that we can create custom pages within the top header, like in https://guole.fun/: 
![image](https://user-images.githubusercontent.com/323248/121000210-3c89a500-c78a-11eb-90aa-5ae57c80e984.png)

[Kuole-o](https://github.com/kuole-o/kuole-o.github.io) did it by adding new folder with html pages in the main folder, but it could be great to work on a better way, like adding new folders in the content folder, like here:
![image](https://user-images.githubusercontent.com/323248/121000522-9be7b500-c78a-11eb-846b-e6b85dc40647.png)

**Comment by g1eny0ung** [comment]
Good idea! I will think about how to implement this feature.

**Comment by kuole-o** [comment]
+1，希望考虑支持下多级菜单，子菜单栏这样。尤其手机，顶部空间有限，icon只能放那几个……  
  
另外，也许也可以考虑下，某些人只想用纯文本或文本+icon形式的菜单布局。  
  
移动端，或者尝试下侧边栏？只是可能有点不和谐

**Comment by Darthagnon** [comment]
Idea: What about putting the "Archives", "Tags", "Categories" icons to the top header, instead of mixed with the tag cloud?

**Comment by g1eny0ung** [comment]
> Idea: What about putting the "Archives", "Tags", "Categories" icons to the top header, instead of mixed with the tag cloud?

This can be an option I think.

**Comment by g1eny0ung** [comment]
Starting from https://github.com/g1eny0ung/hugo-theme-dream/releases/tag/v3.4.1, Dream supports specifying arbitrary custom nav items (icon-based or text-based, for a good visual experience, Icon-based and text-based cannot be applied at the same time). You can also reorder them and collapse them. I will not continue to maintain the old major version, so if you're interested in the v3 version, see https://g1en.site/hugo-theme-dream/migrate-to-v3 for more details.
