### ISSUE TITLE
When you set a cover but no image in an article, you have a broken image at the beginning of your article

### ISSUE THREAD

**Issue by PetiPandaRou** [g1eny0ung/hugo-theme-dream#217]
Hello, 

I did an article on my website, with a cover, but I don't want this cover to be at the beginning of my article. 
So I commented the images parameters of my article:
```
---
title: Marque-pages du mois de Juin 2021
date: 2021-06-08
lastmod: 2021-06-08
author: PetiPandaRou
tags: ["bookmarks","read it later", "productivité", "télétravail", "bonheur au travail", "créativité"]
categories: ["Dans ma poche"]
avatar: /me/pikachu.png
cover: img/books.jpg
# images:
#  - 
---
```

But when publishing this article, I add a broken image at the beginning of the article:  
![image](https://user-images.githubusercontent.com/323248/121200971-71722680-c874-11eb-807c-a98e90b32efb.png)

Normally, the cover should be for the homepage cover of the article but not automatically in the article.

**Comment by g1eny0ung** [comment]
You can add `showSummaryCoverInPost = false` or not set this param to remove the cover on the article page.
