### ISSUE TITLE
How can I change font and size?

### ISSUE THREAD

**Issue by rushichaudhari** [g1eny0ung/hugo-theme-dream#222]
Is it possible to change the font?

**Comment by g1eny0ung** [comment]
See https://github.com/g1eny0ung/hugo-theme-dream/issues/189.

**Comment by g1eny0ung** [comment]
I will finish the related works this weekend (Allow to change the fonts in config).

**Comment by g1eny0ung** [comment]
See https://g1eny0ung.site/hugo-theme-dream/#/custom?id=custom-fonts.
