### ISSUE TITLE
TOC not appearing

### ISSUE THREAD

**Issue by yenngee** [g1eny0ung/hugo-theme-dream#226]
Hi! 

Thank you for the lovely theme! I really like it. 

I have been trying to get the table of contents on my rmd file, in the config.toml file, I put fixedNav = true, however, the table of content does not appear. 
![screenshot](https://user-images.githubusercontent.com/39240249/123684737-69f4da80-d880-11eb-9097-eda21689f2c0.JPG)

Can I check how to add the toc to rmd files? 

Thank you!

**Comment by g1eny0ung** [comment]
It seems that you use `# xxx` as the subtitle. The TOC will only render titles of level 2 and below.
