### ISSUE TITLE
[Bug] Background image disappears in Firefox

### ISSUE THREAD

**Issue by Darthagnon** [g1eny0ung/hugo-theme-dream#227]
Example screenshots:

Ungoogled Chromium v90:
![Hugo Theme Dream UnChromium v90](https://user-images.githubusercontent.com/20792748/123852193-f2708b00-d913-11eb-9fd2-54ca9e49500e.jpg)

Firefox ESR v78:
![Hugo Theme Dream Firefox ESR78](https://user-images.githubusercontent.com/20792748/123852206-f7cdd580-d913-11eb-8d72-dbeacf12365a.png)

**Comment by suye0620** [comment]
Me Too，So Sad about It

**Comment by Darthagnon** [comment]
I had an idea of doing a JS script that picks an image via weighted random selection from a pool (list of URLs or website folder of images) and changing it on every page load, with a fallback image in case of NoScript or incompatible browser. It could fix this at the same time. I'll take a look later while fixing some stuff to use it on my site.
