### ISSUE TITLE
Navigation is JS-dependent?

### ISSUE THREAD

**Issue by Darthagnon** [g1eny0ung/hugo-theme-dream#228]
I noticed when visiting the demo site and blog with this really nice theme, that the navigation buttons/links don't work when NoScript is enabled. 

Shouldn't the navigation just be images/SVGs with links? Is it JS-dependent somehow?

Would be nice, in case of NoScript, older browsers, Tor or limited connectivity, where the JS is disabled, for the navigation to still work on a basic level.

**Comment by g1eny0ung** [comment]
Yep. Some links use `window.location.href` to jump. I think you are right. It should let the basic navigation don't rely on JS.

**Comment by g1eny0ung** [comment]
Solve in d0578a6.
