### ISSUE TITLE
Adding support of different image style

### ISSUE THREAD

**Issue by PetiPandaRou** [g1eny0ung/hugo-theme-dream#231]
Depending the alignment that you want:
- right
- left
- center
- adding border
- justify

Source where I had the idea: https://www.xaprb.com/blog/how-to-style-images-with-markdown/

**Comment by g1eny0ung** [comment]
Sounds good. I will try to provide some options to align the images.

**Comment by Darthagnon** [comment]
Has anyone considered [PhotoSwipe](https://photoswipe.com/)? It's used quite effectively in [Hugo Theme Stack](https://github.com/CaiJimmy/hugo-theme-stack). Gives albums (and a bit of alignment?)

**Comment by g1eny0ung** [comment]
This behavior can be implemented by customizing the css.
