### ISSUE TITLE
Add html link in footerBottomText

### ISSUE THREAD

**Issue by raiden076** [g1eny0ung/hugo-theme-dream#237]
Can I add a HTML link in the footer bottomtext,
like <a href="https://www.w3schools.com/" target="_blank">Visit W3Schools!</a> something this?

I have tried to add this but it's giving error like

`~\Projets\website_Sayan-v3  master ≡  4.948s`
`❯ hugo new posts/test3.md`
`Error: "C:\Users\arkap\Projets\website_Sayan-v3\config.toml:42:1": unmarshal failed: Near line 42 (last key parsed 'params'): expected a top-level item to end with a newline, comment, or EOF, but got 'h' instead`

**Comment by g1eny0ung** [comment]
Yes. It is possible to do so.

**Comment by raiden076** [comment]
My bad, I've already done it 😝
Forgot to close the issue.
