### ISSUE TITLE
whatsapp share option

### ISSUE THREAD

**Issue by raiden076** [g1eny0ung/hugo-theme-dream#239]
Can you add share via whatsapp option?

**Comment by g1eny0ung** [comment]
Of course. I'll do it later.

**Comment by raiden076** [comment]
I have added the share via WhatsApp option,
It has some issues though,
Please check the PR.

**Comment by g1eny0ung** [comment]
Now you can add arbitrary social links. See https://g1en.site/hugo-theme-dream/social-links.
