### ISSUE TITLE
Google Analytics v4

### ISSUE THREAD

**Issue by Qinjianbo** [g1eny0ung/hugo-theme-dream#249]
How can I use Google Analytics v4？
My googleAnalytics is G-839GW747XX, It`s prefix is G, not UA.

**Comment by g1eny0ung** [comment]
Refer to https://gohugo.io/templates/internal#google-analytics, upgrade Hugo to at least [v0.82.0](https://github.com/gohugoio/hugo/releases/tag/v0.82.0) to use v4 version.

**Comment by Qinjianbo** [comment]
Yes, I read the document above, then I use v4 by changing the code
```
{{ if .Site.GoogleAnalytics }}
    {{ template "_internal/google_analytics_async.html" . }}
{{ end }}
```
to
```
{{ if .Site.GoogleAnalytics }}
    {{ template "_internal/google_analytics.html" . }}
 {{ end }}
```
where the code at dream/layouts/_default/baseof.html.

**Comment by Qinjianbo** [comment]
I know what should I do. I only need rewrite the baseof.html in my own layouts.Thanks a lot.
