### ISSUE TITLE
Disqus comments not appearing

### ISSUE THREAD

**Issue by rushic24** [g1eny0ung/hugo-theme-dream#251]
Which library would you suggest for comments? Currently I'm using disqus but sometimes the comments appear and sometimes they don't. Can you please take a look what is wrong?

[link to site](https://github.com/rushichaudhari/rushichaudhari.github.io)

**Comment by rushic24** [comment]
@g1eny0ung can you also look into this https://g1eny0ung.site/, it appears dead.

**Comment by rushic24** [comment]
After some debugging I think disqus comments work in chrome but not in firefox. 
I even in firefox incognito thinking some extension might be blocking it. But its still the same there. 
But in the same firefox I'm able to view other hugo based websites with disqus comments. 

The console in firefox shows this
![Screenshot-2](https://user-images.githubusercontent.com/6279035/143689448-1517480e-a48b-47ee-802e-7a495cc60e73.png)

**Comment by g1eny0ung** [comment]
> After some debugging I think disqus comments work in chrome but not in firefox. I even in firefox incognito thinking some extension might be blocking it. But its still the same there. But in the same firefox I'm able to view other hugo based websites with disqus comments.
> 
> The console in firefox shows this ![Screenshot-2](https://user-images.githubusercontent.com/6279035/143689448-1517480e-a48b-47ee-802e-7a495cc60e73.png)

After I tested I think it's related to Disqus itself or the network.

**Comment by rushic24** [comment]
> > After some debugging I think disqus comments work in chrome but not in firefox. I even in firefox incognito thinking some extension might be blocking it. But its still the same there. But in the same firefox I'm able to view other hugo based websites with disqus comments.
> > The console in firefox shows this ![Screenshot-2](https://user-images.githubusercontent.com/6279035/143689448-1517480e-a48b-47ee-802e-7a495cc60e73.png)
> 
> After I tested I think it's related to Disqus itself or the network.

Hmm, but why do some blogs with disquis still load in firefox? Also can you suggest a good alternative to disquis?

**Comment by g1eny0ung** [comment]
> Hmm, but why do some blogs with disquis still load in firefox?

🤔 Not really sure, you can google why it doesn't work anymore and see what similar situations there are.

> Also can you suggest a good alternative to disquis?

From what I know, I recommend this: https://github.com/utterance/utterances.
