### ISSUE TITLE
請問要如何換行 空白 

### ISSUE THREAD

**Issue by PingStyle** [g1eny0ung/hugo-theme-dream#252]
我用了您的框架，架了一個BLOG
感覺很不錯，謝謝您

但有個小問題

就是markdown編輯時文字一定要間格一行空白
才可以正確顯示出我要的內容
不換行，文字就擠在同一行

不知道有沒有辦法，可以調整換行的部分呢

**Comment by g1eny0ung** [comment]
❤️ 感谢使用，这种情况可以直接写 HTML 标签，比如：

```text
这是一行文字<br />这是下一行文字
```

会渲染成：

这是一行文字<br />这是下一行文字
