### ISSUE TITLE
When you put no cover, the rendering is weird.

### ISSUE THREAD

**Issue by rushic24** [g1eny0ung/hugo-theme-dream#253]
![Screenshot from 2021-12-26 08-36-38](https://user-images.githubusercontent.com/6279035/147412235-12fd78ea-d8c0-4c50-8bec-4713a93ecdab.png)

Can we hide that Small square and the text beside it at the top if there is no cover?

**Comment by rushic24** [comment]
Nvm, I commented this 
https://github.com/g1eny0ung/hugo-theme-dream/blob/master/layouts/_default/summary.html#L6

and removed all `cover:''`, it worked

**Comment by g1eny0ung** [comment]
Oops, I think I should update the template to not render the weird `a` tag when `cover` is an empty string or not set.

**Comment by g1eny0ung** [comment]
Fixed in d67f7842a2c7f7784d36502de51580abff38a596.
