### ISSUE TITLE
无法将最后修改时间设置为git提交时间

### ISSUE THREAD

**Issue by shenmo7192** [g1eny0ung/hugo-theme-dream#259]
附上我的config.toml
https://gitee.com/shenmo7192/shenmo7192/blob/master/config.toml

**Comment by g1eny0ung** [comment]
这个没有做，我稍后加一下。感谢指出 ❤️。

**Comment by g1eny0ung** [comment]
@shenmo7192 我试了试好像没有问题。我最初以为需要额外支持一下，但其实不用。我猜你可能是处在开发模式下，build 一下试试看。

<img width="732" alt="image" src="https://user-images.githubusercontent.com/15034155/156197061-6918a982-fd96-4843-a419-2027713eefef.png">

**Comment by shenmo7192** [comment]
> 我查到是为什么了，你的问题跟这个有关：[gohugoio/hugo#3071](https://github.com/gohugoio/hugo/issues/3071)

非常感谢！我真是没想到会是编码问题！踩坑+1  
Non-ascii filename breaks lastmod peaceiris/actions-hugo#496  
  
又可以水一篇博客了~
