### ISSUE TITLE
Plan to rewrite with Bulma

### ISSUE THREAD

**Issue by g1eny0ung** [g1eny0ung/hugo-theme-dream#263]
Since https://github.com/semantic-org/semantic-ui and its active fork https://github.com/fomantic/fomantic-ui haven't released a new version in a long time. I plan to rewrite this theme with https://bulma.io/.

**Comment by Darthagnon** [comment]
How big of a rewrite will this be? I've been pushing lots of small changes to my fork (will add them to the pull request once I've unbroken it), hopefully they're still usable.

**Comment by g1eny0ung** [comment]
> How big of a rewrite will this be? I've been pushing lots of small changes to my fork (will add them to the pull request once I've unbroken it), hopefully they're still usable.
> 
> EDIT: Shouldn't it be v3.0, since it's a breaking change?

The entire UI won't be affected. I will just replace the existing classes with Bluma's classes. That's why I decided to go with `2.1` as the next release since the `2.0` version has been released yet.

**Comment by g1eny0ung** [comment]
It's ok to propose some changes to the current version (with semantic-ui). I will handle the migration to Bulma.

**Comment by g1eny0ung** [comment]
This issue is outdated because I've finally adopted tailwindcss and daisyUI.
