### ISSUE TITLE
Featured posts

### ISSUE THREAD

**Issue by 0xrushi** [g1eny0ung/hugo-theme-dream#265]
Hi, Is it possible to add a featured: True post to keep it always on top ?

**Comment by Darthagnon** [comment]
Might be possible with masonry js and .stamp
https://masonry.desandro.com/options.html#stamp
https://codepen.io/desandro/pen/AJNPZG

I'll be trying to implement it in [my fork](https://github.com/Darthagnon/hugo-theme-dream) eventually

**Comment by g1eny0ung** [comment]
This can be done by adjusting the post's weight to move it before other posts. https://gohugo.io/getting-started/glossary/#weight
