### ISSUE TITLE
Search doesn't work in production

### ISSUE THREAD

**Issue by congfandi** [g1eny0ung/hugo-theme-dream#270]
Hi There, i have been use you theme, THanks alot for it. but i have some problemo here with search functionality

I dont know what should i do because its working well in my local computer but not in my production server. here nyspesification

Prod Server : Use Netlify
Dev Computer : MacOS Monterey

and here my website : https://thengoding.com

i have been putting 

```
[outputs]
  home = ["HTML", "RSS", "JSON"]
```

in my config.toml

can you help me with that, is there any document can i read ? Thanks.

**Comment by g1eny0ung** [comment]
Sorry...I overlooked this issue for a long time. 🥲 Since I've rebuilt the search feature in v3, would you like to try it and see if it works currently? Now there's no need to set `outputs`.

https://g1en.site/hugo-theme-dream/search
