### ISSUE TITLE
Demo is 404

### ISSUE THREAD

**Issue by RoneoOrg** [g1eny0ung/hugo-theme-dream#276]
See [the link in the Readme](https://github.com/g1eny0ung/hugo-theme-dream#intro), pointing to the following page: https://themes.gohugo.io/theme/hugo-theme-dream/

**Comment by Darthagnon** [comment]
The Hugo devs occasionally deprecate themes that haven't been updated recently. I dislike this, as it makes discovery of Hugo themes more difficult, but that's what they do. It was there previously: https://web.archive.org/web/20210423110249/https://themes.gohugo.io/theme/hugo-theme-dream/

In other news, I have an an active fork: https://github.com/Darthagnon/hugo-theme-dream/tree/production

**Comment by g1eny0ung** [comment]
Now point to: https://themes.gohugo.io/themes/hugo-theme-dream. I'll close this issue.
