### ISSUE TITLE
HUGO更新到v0.124.1之后生成站点出现报错

### ISSUE THREAD

**Issue by shinonome-shizuka** [g1eny0ung/hugo-theme-dream#283]
> Error: error building site: render: failed to render pages: render of "term" failed: "/themes/dream/layouts/_default/baseof.html:20:7": execute of template failed: template: _default/list.html:20:7: executing "_default/list.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: _internal/twitter_cards.html:1:15: executing "_internal/twitter_cards.html" at <partial "_funcs/get-page-images" .>: error calling partial: execute of template failed: template: partials/_funcs/get-page-images.html:22:10: executing "partials/_funcs/get-page-images.html" at <$imgParams>: range can't iterate over /

在此之前没有修改过任何文件，辛苦大佬有空看看是哪里的问题。

可能有用的官方issue反馈： #https://github.com/gohugoio/hugo/issues/12210

**Comment by g1eny0ung** [comment]
请问你的 `params.images` 是怎么配置的呢？我看了你附加的 issue 里说这个配置的期望值应该是一个 string list。我又检查了一下我的配置，我确实是使用了 string list。并且我也用了 `v0.124.1` 的版本 build 了一下，没有发现报错。

**Comment by shinonome-shizuka** [comment]
> @shinonome-shizuka 请问你的 `params.images` 是怎么配置的呢？我看了你附加的 issue 里说这个配置的期望值应该是一个 string list。我又检查了一下我的配置，我确实是使用了 string list。并且我也用了 `v0.124.1` 的版本 build 了一下，没有发现报错。

`[params]
images =  "/me/background@zetsubo.jpg"`

把images全部注释掉之后就没报错了。可能是最早刚开始折腾的时候留下来没改掉的东西。

**Comment by g1eny0ung** [comment]
Ok, 可以再看看是什么原因。
