### ISSUE TITLE
你好使用了您的主题，非常好 ，不过现在遇到了一个问题

### ISSUE THREAD

**Issue by uoxiangfei** [g1eny0ung/hugo-theme-dream#287]
就是我在本地windows测试 都没问题。我生成public文件后，上传服务器，可是点击首页的时候总是连接到http://localhost:1313/本地地址去了。 而写的文章却可以自动识别域名 都能正常访问。 希望你能帮助到我。谢谢！

**Comment by g1eny0ung** [comment]
能否提供一下您的线上地址呢？我去看一下。

**Comment by uoxiangfei** [comment]
[x.yhehe.com ](https://x.yhehe.com/)我使用的是你现有程序

**Comment by g1eny0ung** [comment]
有设置这个配置吗？https://gohugo.io/getting-started/configuration/#baseurl

这个配置控制了首页的地址。

**Comment by uoxiangfei** [comment]
baseURL = 'https://x.yhehe.com/'  我是这样设置的

**Comment by uoxiangfei** [comment]
文章页 地址正常~实在不知道问题出在哪里

**Comment by g1eny0ung** [comment]
> 文章页 地址正常~实在不知道问题出在哪里

文章使用的是相对路径，所以不受影响。

**Comment by g1eny0ung** [comment]
> 好的 我试验一下 确实现在是hugo server 生成的文件传上去了

好的，那应该就是这个原因了。具体参数可以参考：https://gohugo.io/commands/hugo/

**Comment by uoxiangfei** [comment]
好了 很感谢你的帮助 ，是不是留言把[services]
[services.disqus]
shortname = "g1eny0ung"换成我的申请的名就行了

**Comment by g1eny0ung** [comment]
> 好了 很感谢你的帮助 ，是不是留言把[services] [services.disqus] shortname = "g1eny0ung"换成我的申请的名就行了

是的，还有些其他的参数比如 `[services.googleAnalytics]`，`utterancesRepo`，这些也都要改掉或者去掉，这些也是跟个人相关的。

**Comment by uoxiangfei** [comment]
嗯 好的 我尝试修改一下~再次感谢！

**Comment by g1eny0ung** [comment]
ok，那我就先关闭这个 issue 了，如果有其他问题，可以再打开新的提问。😃

**Comment by uoxiangfei** [comment]
好的 打搅了！
