### ISSUE TITLE
请问首页怎样才能选择显示多少篇文章

### ISSUE THREAD

**Issue by uoxiangfei** [g1eny0ung/hugo-theme-dream#288]
在那个文件下下修改 谢谢

**Comment by g1eny0ung** [comment]
你想要的应该是这个配置：https://gohugo.io/templates/pagination/#configuration。修改 `pagerSize`。

**Comment by uoxiangfei** [comment]
谢谢 已经改好了~ 对你的耐心回答重心感谢

**Comment by uoxiangfei** [comment]
不知道该主题可以实现浏览一篇文章的时候 结尾处可以显示上一篇 下一篇，这样就能方便阅览。目前情况，阅读一篇文章后 只能点主页或者归档再去浏览文章。如果可以实现的话 我应该在哪里学习教程

**Comment by g1eny0ung** [comment]
这个 Google 一下就可以找到相关的教程了，比如搜索：hugo implement next previous post。

我可以去实现一下这个功能，实现完了我可以艾特你进行参考。

**Comment by uoxiangfei** [comment]
好的，感谢，如果您也需要~ 还请大佬把文章目录加上。方便阅读，类似于下面的这样图
![image](https://github.com/user-attachments/assets/a0951174-3f8b-4c0e-a495-1f51517eb5fd)

**Comment by g1eny0ung** [comment]
@uoxiangfei 现在使用这个参数即可显示上/下一篇的按钮：https://g1en.site/hugo-theme-dream/params-configurations#showprevnextpost--true

代码请参考这个 commit：https://github.com/g1eny0ung/hugo-theme-dream/commit/950e07c9e4530df0058857b1d4b83e416852df88

TOC 我也准备做，但是我需要花时间设计一下。
