### ISSUE TITLE
Support TOC in v3

### ISSUE THREAD

**Issue by g1eny0ung** [g1eny0ung/hugo-theme-dream#289]
I should migrate the TOC functionality from v2 to v3.

**Comment by uoxiangfei** [comment]
太好了 ，可惜我对上一篇下一篇 还没能好~ 我把hasTwitterEmbed = true 打开 可是帖子页面并没有显示上一篇下一篇。
是不是我没有嵌入https://publish.twitter.com/生成的 Twitter 组件，的原因呢

**Comment by g1eny0ung** [comment]
@uoxiangfei 参数看错了，是这个：`showPrevNextPost = true`。
