### ISSUE TITLE
请问我打开了TOC 不知道为什么页面并不显示目录。

### ISSUE THREAD

**Issue by uoxiangfei** [g1eny0ung/hugo-theme-dream#291]
除了要修改stickyNav = true  还需要修改哪里吗  我下的是博主在使用的博客文件。
还有就是博客页面 横项一页显示不完，就会导致底部出现横项滚动条，不知道是不是我显示器的原因呢。请博主注意看一下！

**Comment by g1eny0ung** [comment]
可以给个 demo 吗？光从你的描述我没办法定位到问题

**Comment by uoxiangfei** [comment]
https://blog.yhehe.com/
就是页面底部横项显示不完，会出现滚动条。

**Comment by uoxiangfei** [comment]
还有一篇长的文章能显示返回顶部 就好了 。

**Comment by uoxiangfei** [comment]
还有一个问题 我的博客是 在本地生成好的public文件，上传服务器使用。在本地可以显示TOC目录 ，上传服务器后就不显示了 ，不知道问题出在哪里~

**Comment by g1eny0ung** [comment]
> [blog.yhehe.com](https://blog.yhehe.com/) 就是页面底部横项显示不完，会出现滚动条。

没有复现，可以再具体一点儿吗？

**Comment by g1eny0ung** [comment]
> 还有一个问题 我的博客是 在本地生成好的public文件，上传服务器使用。在本地可以显示TOC目录 ，上传服务器后就不显示了 ，不知道问题出在哪里~

这个我也不清楚。

**Comment by uoxiangfei** [comment]
> > [blog.yhehe.com](https://blog.yhehe.com/) 就是页面底部横项显示不完，会出现滚动条。
> 
> 没有复现，可以再具体一点儿吗？

 就是现在排版有点宽一次显示不完，
![微信图片_20240729214906](https://github.com/user-attachments/assets/bdfd343f-bab5-4e9f-abea-132fd93948be)
点击出现左右移动的情况

**Comment by g1eny0ung** [comment]
我这边依旧没有复现出来。

**Comment by uoxiangfei** [comment]
> 我这边依旧没有复现出来。

你左右拉不动吗，没有出现滚动条吗

**Comment by g1eny0ung** [comment]
> > > 我这边依旧没有复现出来。
> > 
> > 
> > 你左右拉不动吗，没有出现滚动条吗
> 
> 我浏览你网站的时候也会出现横项滚动条。难道是我浏览器的问题？我现在用的Google Chrome并且在Microsoft Edge也显示。

我用的是 mac，那我回头找台 windows 的电脑测试一下。

**Comment by g1eny0ung** [comment]
横项滚动条的问题我应该解决了，可能是因为你设置了“一直显示滚动条”这个系统选项，我更新了代码覆盖了这个情况，可以再尝试一下。

**Comment by uoxiangfei** [comment]
> 横项滚动条的问题我应该解决了，可能是因为你设置了“一直显示滚动条”这个系统选项，我更新了代码覆盖了这个情况，可以再尝试一下。

浏览别的网站都不会出出现。算了也不影响什么。不知道大佬可以加上返回顶部的功能吗~
