### ISSUE TITLE
markdown的代码块部分缺少了滚动条

### ISSUE THREAD

**Issue by crisite** [g1eny0ung/hugo-theme-dream#293]
你好, 大佬你的博客样式我很喜欢, 直接从 `hexo` 迁移到 `hugo`~
然后现在碰到了个问题

### 问题描述
![image](https://github.com/user-attachments/assets/363d6627-8e60-40d7-a60a-afc0e17dd71d)
如图所示
在代码块内的内容过长的时候,好像缺少了一个滚动条(这是什么配置选项吗, 我并没有找到)

### 演示地址
https://crisite-github-io.vercel.app/posts/archlinux-dwm/

**Comment by crisite** [comment]
另外markdown语法的 两个 ` 中间的代码, 在电脑端显示正常, 
但是在手机端的背景色和字体色过于接近导致无法识别

![4fd74c99fc8b598925f5f053de44aa5](https://github.com/user-attachments/assets/e771feb0-1280-4492-b807-6f11b9e112c3)

**Comment by g1eny0ung** [comment]
代码溢出的问题我在 https://github.com/g1eny0ung/hugo-theme-dream/commit/ae9f906b7d6ab65e4078681f80a8596106f18fac 解决了，可以再试试。

关于 code block 背景色的问题，这个你可以根据你的背景色进行调整，具体做法可以参考 https://github.com/tailwindlabs/tailwindcss-typography#element-modifiers

然后你需要修改源码的这一行：https://github.com/g1eny0ung/hugo-theme-dream/blob/84a4898e0b49c7623262bfb21ada040e6ca6e5de/layouts/_default/single.html#L46

最后运行 `pnpm css` 来生成样式。
