### ISSUE TITLE
Enhancement Proposal for SEO Improvement - Adding Keywords Support

### ISSUE THREAD

**Issue by MaximoVolynets** [g1eny0ung/hugo-theme-dream#304]
Hello, i hope this message finds you well. Firstly, i want to commend you on the exceptional work you've done with the hugo-theme-dream. 

Proposal:
I've noticed that the theme has strong SEO features, which is great for improving search engine visibility. However, I believe that incorporating support for keywords further enhance the theme's SEO capabilities. Keywords are crucial for search engine optimization and could help improve the theme's effectiveness in targeting specific search queries.
Would it be possible to consider adding a feature or option to include keywords in the theme's meta tags?

If you're open to this idea, I'd be happy to provide further details or collaborate on how this feature could be integrated into the theme.
Thank you for considering this enhancement. I look forward to your thoughts and i'm eager to contribute to making the hugo-theme-dream even better. 

Best regards,
MaximoVolynets

**Comment by g1eny0ung** [comment]
Thank you @MaximoVolynets. Yes, I'm willing to add keywords support, you've made me realize what was missing from this theme.

After my search, I think it is also very easy to complete this enhancement. Hugo provides an embedded template named [schema](https://gohugo.io/templates/embedded/#schema), we can use it in the theme. I will open a PR and let you know.

Also if you have some additional suggestions, we can continue to discuss them in this issue thread.

**Comment by g1eny0ung** [comment]
A related PR has been opened.
