### ISSUE TITLE
[Bug]: Missing "About" when using Italian language

### ISSUE THREAD

**Issue by dSyncro** [g1eny0ung/hugo-theme-dream#313]
### Version

master

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Describe the bug

When using italian language as `defaultContentLanguage` the about section does not appear in the navbar.
This is due to the missing translation key in `it.toml`.

In italian language there really isn't a translation for "About" as intended in this case nevertheless I think a sane default like the following should be added anyway

```
[about]
other = "Chi siamo"
```

It is particularly evident in the side-menu item on mobile.

I also think it would be appropriate to add a mechanism to allow user to customize it without tinkering with the theme source code (this might already exist but I could not find any documentation on it).

### To Reproduce

Just set `defaultContentLanguage` to `it`. On desktop no navbar item is shown. On mobile the item is missing its label.

![Screenshot 2024-09-04 122933](https://github.com/user-attachments/assets/89a1b3cd-fa90-467b-874d-1f4cbe0837fa)

**Comment by g1eny0ung** [comment]
I see. Indeed, as I'm not familiar with languages other than Chinese and English, their translations haven't been updated. I'll supplement this "about" translation to `it.toml`.

> I also think it would be appropriate to add a mechanism to allow user to customize it without tinkering with the theme source code (this might already exist but I could not find any documentation on it).

I'm also not sure if it can be. I will take an investigation.

**Comment by g1eny0ung** [comment]
Fixed in c8c1096.
