### ISSUE TITLE
[Feature]: 增加Google AdSense 的功能

### ISSUE THREAD

**Issue by WinPoss** [g1eny0ung/hugo-theme-dream#324]
### Feature request

博主，可以增加Google AdSense 的功能吗？在首页第一个“豆腐块”和文章页面右下角展示广告。

很喜欢这个主题，如果有个Google AdSense 的功能就完美了。

### Proposed solution

![image](https://github.com/user-attachments/assets/fee494ce-425a-4814-bfe0-63f0800ec02b)
![image](https://github.com/user-attachments/assets/37420231-2f81-47e0-b857-8622e4c19660)

**Comment by g1eny0ung** [comment]
我在 [adcf326](https://github.com/g1eny0ung/hugo-theme-dream/commit/adcf3266e82ef4a1d029eb32e4e46d5b8849b08a) 这个 commit 中加了一个 slot，现在你可以在文章页面的 TOC 下面插入 adsense，方法是在 `layouts/partials/` 下面创建一个 `adsense.html` 文件。由于我自己还没有权限开通 adsense，所以在首页上插入的话，我还得再找找测试方法。

**Comment by WinPoss** [comment]
> 我在 [adcf326](https://github.com/g1eny0ung/hugo-theme-dream/commit/adcf3266e82ef4a1d029eb32e4e46d5b8849b08a) 这个 commit 中加了一个 slot，现在你可以在文章页面的 TOC 下面插入 adsense，方法是在 `layouts/partials/` 下面创建一个 `adsense.html` 文件。由于我自己还没有权限开通 adsense，所以在首页上插入的话，我还得再找找测试方法。

好的，我试试，博主大爱！

**Comment by g1eny0ung** [comment]
😉不客气，因为这个 issue 的问题已经被 #315 追踪了，所以我就先把它关掉了。
