### ISSUE TITLE
[Bug]: Hamburger menu links don't not work on Safari

### ISSUE THREAD

**Issue by lskbr** [g1eny0ung/hugo-theme-dream#325]
### Version

master

### What browsers are you seeing the problem on?

Safari

### Describe the bug

When using: 
[params.navItems]
pt = { href = "/pt", title = "Português", target = "_self" }
en = { href = "/en", title = "English", target = "_self" }
fr = { href = "/fr", title = "Français", target = "_self" }

The links are correctly displayed on a desktop screen. Hamburger menu links also work perfectly.
Testing on iOS Safari or MacOS Safari, the links won't work when the hamburger menu is displayed.
If we rotate the screen, the options work again (outside the hamburger menu).
There is no error message in the console. It seems to be related to how Safari handles z-index.

Example build with problems:
https://inovamakers.com/en/

### To Reproduce

Open Safari on iPhone or macOS.
Make the hamburger menu show up. In the desktop, you can narrow the window to force it.
Open the hamburger menu. Try to click on English, Português or Français options. Nothing happens.

**Comment by g1eny0ung** [comment]
After testing, I found that this is indeed a bug related to Safari and I've fixed it. Thanks for pointing this out! 👍🏼
