### ISSUE TITLE
[Bug]: No Footer on the About Page

### ISSUE THREAD

**Issue by musingmaddy** [g1eny0ung/hugo-theme-dream#328]
### Version

v3.8.2

### What browsers are you seeing the problem on?

Chrome

### Describe the bug

The about page does not have a footer bar or Light/Dark mode button.

**Comment by g1eny0ung** [comment]
Hi @musingmaddy, thanks for pointing out this issue. I didn't append the footer on about page before. Now it is fixed, you can try it again with the latest code.
