### ISSUE TITLE
Feedback for “Custom Theme”

### ISSUE THREAD

**Issue by tempire** [g1eny0ung/hugo-theme-dream#337]
`customCSS = ["css/custom.css"] # Files in the list will be loaded in order.`

Where in the directory structure is css/ expected?

**Comment by g1eny0ung** [comment]
I've updated docs to indicate where custom files should be placed: https://g1en.site/hugo-theme-dream/custom.

Thanks for your question, which helped me find the missing part of the documentation. Now I'll close it. Feel free to open a new issue if you still have some questions. 😃
