### ISSUE TITLE
[Feature]: 文章页面的TOC添加滚动功能

### ISSUE THREAD

**Issue by Vincent-ice** [g1eny0ung/hugo-theme-dream#339]
### Feature request

当TOC比较长的时候会被截断, 且无法单独滚动
![image](https://github.com/user-attachments/assets/028ca5fd-1e6f-4397-bfdd-59a44aa8137a)
仅当滚动到页面底端时才会滚动到下面
[我的页面](https://vincent-ice.github.io/study-materials/posts/%E5%BE%AE%E6%9C%BA%E5%8E%9F%E7%90%86)

### Proposed solution

maybe过长的时候可以被滚动, 方便跳转

### Additional context

like 文档里面的那种 On this page 的样式

**Comment by g1eny0ung** [comment]
Hi @Vincent-ice，感谢你指出了问题。我在 #340 针对这个问题做了改进，有时间可以帮忙试一试基于这个 PR 你能否顺利地滚动 TOC 呢？

**Comment by Vincent-ice** [comment]
Hi @g1eny0ung ! 感谢对我的问题的修改! 
我测试下来可以顺利滚动, 有个小问题是TOC仅在页面显示正文时才可以被滚动. 如果处于最上部的标题处时滚动的会是页面而非TOC. 

无法滚动TOC, 只可滚动页面: 
![image](https://github.com/user-attachments/assets/68d8cd4a-ce55-4b5d-9dc6-9a4dd1c5739a)
从正文部分开始可正常滚动TOC: 
![image](https://github.com/user-attachments/assets/345edcb7-b840-441e-b0f5-78f2ae794f73)

**Comment by g1eny0ung** [comment]
@Vincent-ice [`d5f0ba2` (#340)](https://github.com/g1eny0ung/hugo-theme-dream/pull/340/commits/d5f0ba227f26abdeb585c43e3ce2e6dbacd79d49) 我又更新了一下，这个问题应该被修复了。

**Comment by Vincent-ice** [comment]
@g1eny0ung 前文说的正文部分可滚动似乎是个巧合
真正的问题在当光标在"back"元素范围内时无法滚动TOC

我尝试在显示正面时给"back"元素添加 `display: none` 
https://github.com/g1eny0ung/hugo-theme-dream/blob/d5f0ba227f26abdeb585c43e3ce2e6dbacd79d49/assets/css/output.css#L3641-L3643
在翻转后添加`display: block`
https://github.com/g1eny0ung/hugo-theme-dream/blob/d5f0ba227f26abdeb585c43e3ce2e6dbacd79d49/assets/css/output.css#L3618-L3620
后可以解决

**Comment by g1eny0ung** [comment]
是的，但不光是 back。front 和 back 均使用了绝对定位，它们在页面还没有开始滚动的情况下遮挡了 TOC 部分，这就导致了 TOC 无法接收到滚动事件。

至于使用 `display: none` 会让页面在初始化的时候无法对 back 部分应用 masonry layout 的效果，所以不可以这样做。

**Comment by g1eny0ung** [comment]
> @Vincent-ice [`d5f0ba2` (#340)](https://github.com/g1eny0ung/hugo-theme-dream/pull/340/commits/d5f0ba227f26abdeb585c43e3ce2e6dbacd79d49) 我又更新了一下，这个问题应该被修复了。

关于这个改动，由于我这个博客主题它有一个翻转动效去显示“关于”页面，所以会存在 `.front` 和 `.back` 两部分内容。这两部分内容没办法改成相对定位，因为如果改成相对定位的话，那么假设在 `.front` 中的内容没有足够的高度的话，back 就会堆叠在 front 的下方：

<img width="1581" alt="image" src="https://github.com/user-attachments/assets/a1c6d696-16d0-45a6-ad20-1539e0b214a7" />

后来我用了一种投机取巧的方式，先让 back 部分向左偏移了 25% (`translateX(-25%)`)，这样它就不会遮挡住 TOC 的部分了，然后在翻转后再将它重置。这样虽然翻转动画效果出现了些许的改变（肉眼还是难以察觉的），但是我觉得还可以接受。

@Vincent-ice 有时间了可以再尝试一下。

**Comment by Vincent-ice** [comment]
我用下来完全没有问题！翻转看起来也没有突兀感
@g1eny0ung 感谢您的修改

**Comment by g1eny0ung** [comment]
Ok，那我就合并那个 PR 了。
