### ISSUE TITLE
Feedback for “Quick Start”

### ISSUE THREAD

**Issue by Promis-E** [g1eny0ung/hugo-theme-dream#342]
Hi there. Firstly, thank you for the Hugo theme!. In the readme you instruct the users to git clone 'link'  dream and add the theme="dream" line to a hugo.toml file, but in your hugo.example.toml file (which we can download) , you use hugo-themes-dream. It is not a major issue to correct , but a newby might get confused.

Secondly , I ahve downloaded and followed the instructions, the site runs but it does no display as per your dream site. 

![imagen](https://github.com/user-attachments/assets/12779761-30e7-4049-90c1-3bdcad3d0097)

Is there more information I can read to find out why this site on localhost does not work for me?

Thanks again

**Comment by g1eny0ung** [comment]
In #344, I updated the install instructions.

**Comment by g1eny0ung** [comment]
I'll merge the PR first. If you still encounter other problems, please feel free to open a new issue.
