### ISSUE TITLE
Avatar not displayed after a category/tag is selected

### ISSUE THREAD

**Issue by MarcusE1W** [g1eny0ung/hugo-theme-dream#4]
Hi 
I noticed that the avatar is shown nicely on the start page.
However, if I filter articles by category or tag the avatar is not shown anymore and the small image not found icon appears.

My avatar image is in the /static folder and the config.toml parameter is like this
`avatar = "raspberry-logo.jpg"`

Any idea how to solve that ?

Hugo 0.31.1
Theme download from 7 Jan 2018

**Comment by g1eny0ung** [comment]
It's easy to solve it. add '/' at the front of your avatar. Like `avatar = "/raspberry-logo.jpg"`

This makes the image URL link relative to root, not by tag or category.

**Comment by MarcusE1W** [comment]
Thanks :-)
