### ISSUE TITLE
not showing posts

### ISSUE THREAD

**Issue by kapcom01** [g1eny0ung/hugo-theme-dream#9]
Hello,
I did the following:
```
snap install hugo
hugo new site kapcom.gr
cd kapcom.gr
git clone https://github.com/g1eny0ung/hugo-theme-dream.git themes/dream
echo 'theme = "dream"' >> config.toml
hugo new posts/my-first-post.md
hugo server -D
```
and then browsed http://localhost:1313/ but the new post is not showing up.

![default](https://user-images.githubusercontent.com/21684/47977974-cd281200-e0c3-11e8-92c3-bce3c4ed5916.png)

```
$ hugo version
Hugo Static Site Generator v0.50 linux/amd64 BuildDate: 2018-10-29T12:39:37Z
```

**Comment by g1eny0ung** [comment]
`hugo new post/my-first-post.md`
 
Make **posts** to **post**. Then the problem should be resolved. 😃

**Comment by kapcom01** [comment]
omg thank you!!

btw I used "posts" because I followed Hugo's Quick Start: https://gohugo.io/getting-started/quick-start/#step-4-add-some-content

Fixed.

**Comment by g1eny0ung** [comment]
Glad to help you. Maybe named post rather than posts is my typo. 😂
