### ISSUE TITLE
The updates broke the theme homepage on the Hugo Themes website

### ISSUE THREAD

**Issue by onedrawingperday** [g1eny0ung/hugo-theme-dream#99]
Hello @g1eny0ung 

The pdemo homepage](https://themes.gohugo.io/theme/hugo-theme-dream/) currently renders empty.

You need to fix this.

Please have a look at the [Hugo Themes README](https://github.com/gohugoio/hugoThemes/blob/master/README.md) for instructions to check your theme with the Build Script.

**Comment by g1eny0ung** [comment]
@onedrawingperday 

Yesterday and today I am rewriting the theme. Because I just updated the `exampleSite` in 741b27628e8d8ed26fc9d2f6c46e633f56849702.

So the demo is broken in the last build. The submodule of my theme still use old examples.

**Comment by onedrawingperday** [comment]
@g1eny0ung 

As [stated](https://gohugo.io/functions/render/) in the Hugo Documentation 

>This example could render a piece of content using the content view located at `/layouts/_default/summary.html`:
```
{{ range .Pages }}
    {{ .Render "summary"}}
{{ end }}
```

As you may have noticed demos hosted at the Hugo Themes showcase inherit their content from the [hugoBasicExample](https://github.com/gohugoio/hugoBasicExample) that does not provide a `posts` section but instead a `post` section.

Therefore your theme's homepage renders empty on the website.

To fix this problem you need to move `summary.html` from the [`layouts/posts/`](https://github.com/g1eny0ung/hugo-theme-dream/blob/master/layouts/posts/summary.html) to `layouts/_default/summary.html`.

Also note that the requirements for maintaining a themes in the Hugo Showcase have been updated and you may want to read them: https://github.com/gohugoio/hugoThemes#theme-maintenance

Please let me know once you look into the above.

Thank you.

**Comment by g1eny0ung** [comment]
@onedrawingperday 

Thanks for the help and the explanation. I already move the `summary.html` to the `_default` folder.

I also update the `exampleSite` folder, because I read this:

> note that for security reasons the content directory on the Hugo showcase will still be published from the Hugo Basic Example repository.

So I remove the custom contents in the `posts` folder.

**Comment by onedrawingperday** [comment]
Thank you for providing the fixes @g1eny0ung 

There is no need to remove the custom `posts` folder. You can keep it for the users who download your theme.

Your theme demo will be fixed at the next scheduled update of Hugo Themes on the 13th of November at 0:00 UTC

**Comment by g1eny0ung** [comment]
@onedrawingperday Thx. 😊
